### PR TITLE
Update documentation to explain @Uses

### PR DESCRIPTION
**Pull request by Legioth**
Based on vaadin/flow#3598

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow-and-components-documentation/39)

### CODE REVIEW

**Comment by gilberto-torrezan** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[polymer-templates/tutorial-template-subtemplate.asciidoc, line 54 at r1](https://reviewable.io:443/reviews/vaadin/flow-and-components-documentation/39#-L7ZSHz6CPol7U5xyiWQ:-L7ZSHz6CPol7U5xyiWR:b8u28aq) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/ef9878e3b3d8fc7a285d57bfd4ee2e30a54b086e/polymer-templates/tutorial-template-subtemplate.asciidoc#L54)):*
> ```AsciiDoc
> Since the client-side implementation of `child-template` depends on a click handler defined from server-side Java, an instance of `ChildTemplate` must be created on the server.
> By using `@Uses(ChildTemplate.class)`, this instance will automatically be created and hooked up with the `<child-template>` element in the parent template based on the `@Tag("child-template")` annotation value.
> ```

would make sense to add a note or warning stating what are the expected errors, logs messages or behaviors if the developer forgets to add `@Uses`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow-and-components-documentation/39)*

**Comment by Legioth** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[polymer-templates/tutorial-template-subtemplate.asciidoc, line 54 at r1](https://reviewable.io:443/reviews/vaadin/flow-and-components-documentation/39#-L7ZSHz6CPol7U5xyiWQ:-L7ZaYkkWVOrOue2Nzns:b-1yj56x) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/ef9878e3b3d8fc7a285d57bfd4ee2e30a54b086e/polymer-templates/tutorial-template-subtemplate.asciidoc#L54)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

would make sense to add a note or warning stating what are the expected errors, logs messages or behaviors if the developer forgets to add `@Uses`?
</blockquote></details>

I'm not sure who would benefit from that kind of note. Someone who has already discovered this page wouldn't need that information, and I don't think we can include anything here that would be specific enough to make this page findable based on the relatively generic errors that would come from that kind of omission.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow-and-components-documentation/39)*

**Comment by gilberto-torrezan** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow-and-components-documentation/39#-:-L7hh1hOpT_0_feDFRK8:bnfp4nl)*

**Comment by caalador** [comment]
Needs manual merge and CLA wants something.

**Comment by Legioth** [comment]
Rebased and and poked at the CLA bot.

**Comment by caalador** [comment]
:lgtm:

---

Reviewed 2 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/39#-:-L9EY7Wf5_YTtGkOQp9I:bnfp4nl)*

**Pull request merged**
