### PR TITLE
Add migration documentation

### PR DESCRIPTION
**Pull request by pleku**
Still missing the links

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow-and-components-documentation/11)

### CODE REVIEW

**Comment by pleku** [comment]
Also need to add this to the menu structure so that it shows in the docs site.

**Comment by caalador** [comment]
Reviewed 5 of 8 files at r1.
Review status: 5 of 8 files reviewed at latest revision, 7 unresolved discussions.

---

*[migration/1-migrating-v8-v10.asciidoc, line 31 at r1](https://reviewable.io:443/reviews/vaadin/flow-and-components-documentation/11#-L5ITSUNUg8UgDUE2yN0:-L5ITSUNUg8UgDUE2yN1:b-bkky5h) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/bf0cacd6729af166ea7f2543e3a9dc886ea930be/migration/1-migrating-v8-v10.asciidoc#L31)):*
> covers the features changed or removed
covers features that have changed or been removed

---

*[migration/1-migrating-v8-v10.asciidoc, line 42 at r1](https://reviewable.io:443/reviews/vaadin/flow-and-components-documentation/11#-L5ITHznPPNcbDeH31R_:-L5ITHznPPNcbDeH31Ra:b-7pom58) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/bf0cacd6729af166ea7f2543e3a9dc886ea930be/migration/1-migrating-v8-v10.asciidoc#L42)):*
> building UI
building UIs

---

*[migration/1-migrating-v8-v10.asciidoc, line 42 at r1](https://reviewable.io:443/reviews/vaadin/flow-and-components-documentation/11#-L5ITehqvFlPVUTiMVsu:-L5ITehqvFlPVUTiMVsv:b66ewlm) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/bf0cacd6729af166ea7f2543e3a9dc886ea930be/migration/1-migrating-v8-v10.asciidoc#L42)):*
> still the same by using
still the same. By using the ready made components to create beautiful apps is still...

---

*[migration/2-migration-strategies.asciidoc, line 9 at r1](https://reviewable.io:443/reviews/vaadin/flow-and-components-documentation/11#-L5IUHWea-Qi8PggmOTp:-L5IUHWea-Qi8PggmOTq:b4tnz15) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/bf0cacd6729af166ea7f2543e3a9dc886ea930be/migration/2-migration-strategies.asciidoc#L9)):*
> the need for migration is always application and business specific. There are several options you should consider.
There are several migration strategies to consider as the need for migration is always application and business specific.

---

*[migration/2-migration-strategies.asciidoc, line 21 at r1](https://reviewable.io:443/reviews/vaadin/flow-and-components-documentation/11#-L5IVAwSJWaadFol0dje:-L5IVAwSJWaadFol0djf:bhrnrua) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/bf0cacd6729af166ea7f2543e3a9dc886ea930be/migration/2-migration-strategies.asciidoc#L21)):*
> run view and components
run views and components

---

*[migration/4-routing-navigation.asciidoc, line 21 at r1](https://reviewable.io:443/reviews/vaadin/flow-and-components-documentation/11#-L5IXYQI4GvrNfas9gtL:-L5IXYQI4GvrNfas9gtM:b2xz3br) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/bf0cacd6729af166ea7f2543e3a9dc886ea930be/migration/4-routing-navigation.asciidoc#L21)):*
> ```AsciiDoc
> @Tag("div")
> @Route(value="company", layout=MainLayout.class)
> public class CompanyComponent extends Component {
> ```

Mixed feelings on this as if you extend Component you need the `@Tag`, but promoting Div sounds strange also.

---

*[migration/6-theming.asciidoc, line 9 at r1](https://reviewable.io:443/reviews/vaadin/flow-and-components-documentation/11#-L5IcEPMm1t_fK1L5vxs:-L5IcEPMm1t_fK1L5vxt:b-nuxugx) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/bf0cacd6729af166ea7f2543e3a9dc886ea930be/migration/6-theming.asciidoc#L9)):*
> and feel for the
and feel of the

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow-and-components-documentation/11)*

**Comment by pleku** [comment]
Review status: 1 of 8 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[migration/1-migrating-v8-v10.asciidoc, line 31 at r1](https://reviewable.io:443/reviews/vaadin/flow-and-components-documentation/11#-L5ITSUNUg8UgDUE2yN0:-L5PIZZngYSUnm93h9RJ:b-896fix) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/1b94942e6fc0024e804b5b88a3856895518c8105/migration/1-migrating-v8-v10.asciidoc#L31)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

> covers the features changed or removed
covers features that have changed or been removed
</blockquote></details>

Done.

---

*[migration/1-migrating-v8-v10.asciidoc, line 42 at r1](https://reviewable.io:443/reviews/vaadin/flow-and-components-documentation/11#-L5ITHznPPNcbDeH31R_:-L5PERXx-gOuRgtkgG2U:b-896fix) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/1b94942e6fc0024e804b5b88a3856895518c8105/migration/1-migrating-v8-v10.asciidoc#L42)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

> building UI
building UIs
</blockquote></details>

Done.

---

*[migration/1-migrating-v8-v10.asciidoc, line 42 at r1](https://reviewable.io:443/reviews/vaadin/flow-and-components-documentation/11#-L5ITehqvFlPVUTiMVsu:-L5PESdpKvOjUNnZ5K4K:b-896fix) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/1b94942e6fc0024e804b5b88a3856895518c8105/migration/1-migrating-v8-v10.asciidoc#L42)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

> still the same by using
still the same. By using the ready made components to create beautiful apps is still...
</blockquote></details>

Done.

---

*[migration/2-migration-strategies.asciidoc, line 9 at r1](https://reviewable.io:443/reviews/vaadin/flow-and-components-documentation/11#-L5IUHWea-Qi8PggmOTp:-L5PGuPIs9Q2waY3OJUU:b-896fix) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/1b94942e6fc0024e804b5b88a3856895518c8105/migration/2-migration-strategies.asciidoc#L9)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

> the need for migration is always application and business specific. There are several options you should consider.
There are several migration strategies to consider as the need for migration is always application and business specific.
</blockquote></details>

Done.

---

*[migration/2-migration-strategies.asciidoc, line 21 at r1](https://reviewable.io:443/reviews/vaadin/flow-and-components-documentation/11#-L5IVAwSJWaadFol0dje:-L5PHcT0N6kFRsKNkqMu:b-896fix) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/1b94942e6fc0024e804b5b88a3856895518c8105/migration/2-migration-strategies.asciidoc#L21)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

> run view and components
run views and components
</blockquote></details>

Done.

---

*[migration/4-routing-navigation.asciidoc, line 21 at r1](https://reviewable.io:443/reviews/vaadin/flow-and-components-documentation/11#-L5IXYQI4GvrNfas9gtL:-L5PHtsblaapm1zURGEM:bb6un1j) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/1b94942e6fc0024e804b5b88a3856895518c8105/migration/4-routing-navigation.asciidoc#L21)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

Mixed feelings on this as if you extend Component you need the `@Tag`, but promoting Div sounds strange also.
</blockquote></details>

Done

---

*[migration/6-theming.asciidoc, line 9 at r1](https://reviewable.io:443/reviews/vaadin/flow-and-components-documentation/11#-L5IcEPMm1t_fK1L5vxs:-L5PIWluLV8HYZ9CFRIp:b-896fix) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/1b94942e6fc0024e804b5b88a3856895518c8105/migration/6-theming.asciidoc#L9)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

> and feel for the
and feel of the
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow-and-components-documentation/11)*

**Comment by Legioth** [comment]
Review status: 1 of 8 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[migration/5-components.asciidoc, line 176 at r2](https://reviewable.io:443/reviews/vaadin/flow-and-components-documentation/11#-L5rnY9WdEQTp81A9tN9:-L5rnY9WdEQTp81A9tNA:b-pa6q1a) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/a1f52147b9504dfb5c7e75ba18a415842129e7c7/migration/5-components.asciidoc#L176)):*
> ```AsciiDoc
> In Vaadin 10 there is no automatic way for this; it is a component specific feature and possible using CSS.
> 
> == Layouts in Vaadin 10
> ```

Could mention something about `setSizeFull()` not having the same effect as previously inside `VerticalLayout` and `HorizontalLayout`. See https://github.com/vaadin/flow/issues/3582

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow-and-components-documentation/11)*

**Comment by pleku** [comment]
Review status: 0 of 12 files reviewed at latest revision, all discussions resolved.

---

*[migration/5-components.asciidoc, line 176 at r2](https://reviewable.io:443/reviews/vaadin/flow-and-components-documentation/11#-L5rnY9WdEQTp81A9tN9:-L6MYMD6-XXCA-g46yED:bb6un1j) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/a1f52147b9504dfb5c7e75ba18a415842129e7c7/migration/5-components.asciidoc#L176)):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

Could mention something about `setSizeFull()` not having the same effect as previously inside `VerticalLayout` and `HorizontalLayout`. See https://github.com/vaadin/flow/issues/3582
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow-and-components-documentation/11)*

**Comment by ZheSun88** [comment]
Reviewed 1 of 7 files at r2, 2 of 11 files at r3.
Review status: 3 of 12 files reviewed at latest revision, 1 unresolved discussion.

---

*[migration/3-general-differences.asciidoc, line 11 at r3](https://reviewable.io:443/reviews/vaadin/flow-and-components-documentation/11#-L6MauMbNZvSwwQPatsr:-L6MauMbNZvSwwQPatss:bmetzb1) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/f0083b9609a417bbe78704e6e7305d521819a239/migration/3-general-differences.asciidoc#L11)):*
> A sublcass of  `UI` is

is there an extra space between `of` and `UI`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow-and-components-documentation/11)*

**Comment by ZheSun88** [comment]
Review status: 3 of 12 files reviewed at latest revision, all discussions resolved.

---

*[migration/3-general-differences.asciidoc, line 11 at r3](https://reviewable.io:443/reviews/vaadin/flow-and-components-documentation/11#-L6MauMbNZvSwwQPatsr:-L6Mbzi3zJKA7QIOO03K:bvhds4t) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/f0083b9609a417bbe78704e6e7305d521819a239/migration/3-general-differences.asciidoc#L11)):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

> A sublcass of  `UI` is

is there an extra space between `of` and `UI`?

</blockquote></details>

looks like it is my mistake. i will resolve it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow-and-components-documentation/11)*

**Comment by ZheSun88** [comment]
Reviewed 1 of 11 files at r3.
Review status: 4 of 12 files reviewed at latest revision, 1 unresolved discussion.

---

*[migration/3-general-differences.asciidoc, line 17 at r3](https://reviewable.io:443/reviews/vaadin/flow-and-components-documentation/11#-L6Me7mysldyzPB5_JmT:-L6Me7mysldyzPB5_JmU:b-ehlzd3) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/f0083b9609a417bbe78704e6e7305d521819a239/migration/3-general-differences.asciidoc#L17)):*
> please [create an issue](https://github.com/vaadin/flow-and-components-documentation/issues/new)

this link is in the `markdown` format, so it doesn't work under `asciidoc`. 
you can use `https://github.com/vaadin/flow-and-components-documentation/issues/new[create an issue]` 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow-and-components-documentation/11)*

**Comment by pleku** [comment]
Review status: 3 of 12 files reviewed at latest revision, 1 unresolved discussion.

---

*[migration/3-general-differences.asciidoc, line 17 at r3](https://reviewable.io:443/reviews/vaadin/flow-and-components-documentation/11#-L6Me7mysldyzPB5_JmT:-L6QA3akQc3QsuOge_L4:b-896fix) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/f0083b9609a417bbe78704e6e7305d521819a239/migration/3-general-differences.asciidoc#L17)):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

> please [create an issue](https://github.com/vaadin/flow-and-components-documentation/issues/new)

this link is in the `markdown` format, so it doesn't work under `asciidoc`. 
you can use `https://github.com/vaadin/flow-and-components-documentation/issues/new[create an issue]` 

</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow-and-components-documentation/11)*

**Comment by denis-anisimov** [comment]
Reviewed 1 of 7 files at r2, 7 of 11 files at r3, 1 of 5 files at r4.
Review status: 8 of 12 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow-and-components-documentation/11)*

**Comment by ZheSun88** [comment]
Reviewed 4 of 5 files at r4.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow-and-components-documentation/11#-L6QDlGwTcvjtcS62I62:-L6QDlGwTcvjtcS62I63:b-5xifqa) (no related file):*
Do we need to mention `vaadin-Iron-List-flow`(the name should be changed in the future) component in the `component` chapter?  Although it is not originally from the `vaadin-element` 

---

*[migration/1-migrating-v8-v10.asciidoc, line 63 at r4](https://reviewable.io:443/reviews/vaadin/flow-and-components-documentation/11#-L6QIw4JYetvq5PCY6Je:-L6QIw4K8vPTiRbMc009:b-69gkll) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/6c18e5e656ac45962fd99c6d1295c32ebfec8cec/migration/1-migrating-v8-v10.asciidoc#L63)):*
> <<5-components#Component Set,Component Sett>>

typo, Component Set

---

*[migration/5-components.asciidoc, line 50 at r4](https://reviewable.io:443/reviews/vaadin/flow-and-components-documentation/11#-L6QSthK4rdtuMN85W5p:-L6QSthK4rdtuMN85W5q:b3ldhg7) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/6c18e5e656ac45962fd99c6d1295c32ebfec8cec/migration/5-components.asciidoc#L50)):*
> ```AsciiDoc
> | GridLayout | - | Not planned. FormLayout, FlexLayout and Board can be used as replacements for many of the use cases
> 
> | HorizontalLayout | HorizontalLayout | https://vaadin.com/elements/vaadin-ordered-layout/java-examples[Demo], more details <<#layouts,later in this chapter>>
> ```

i  didn't find any page for the java examples of `ordered-layout`, maybe we should ask the vaadin.com team for this. Not a blocker

---

*[migration/5-components.asciidoc, line 206 at r4](https://reviewable.io:443/reviews/vaadin/flow-and-components-documentation/11#-L6QCuwbj7TipBcphmjC:-L6QCuwbj7TipBcphmjD:b-r5uizw) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/6c18e5e656ac45962fd99c6d1295c32ebfec8cec/migration/5-components.asciidoc#L206)):*
> (https://github.com/vaadin/flow/issues/2465)[enhancement issue]


https://github.com/vaadin/flow/issues/2465[enhancement issue]

---

*[migration/7-tools-integrations.asciidoc, line 52 at r4](https://reviewable.io:443/reviews/vaadin/flow-and-components-documentation/11#-L6QHBeKS-DDh_3CcmEf:-L6QHBeKS-DDh_3CcmEg:b-kbvv8t) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/6c18e5e656ac45962fd99c6d1295c32ebfec8cec/migration/7-tools-integrations.asciidoc#L52)):*
>  <template>

```
this should be `<template>` to be consistent with all the others used in the guide. 
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow-and-components-documentation/11)*

**Comment by pleku** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow-and-components-documentation/11#-L6QDlGwTcvjtcS62I62:-L6Qe08h1WJ6qUkYBVms:bnxdkks) (no related file):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

Do we need to mention `vaadin-Iron-List-flow`(the name should be changed in the future) component in the `component` chapter?  Although it is not originally from the `vaadin-element` 
</blockquote></details>

There is no corresponding component to it in FW8 so it is not also replacing anything. It is a new feature.

---

*[migration/1-migrating-v8-v10.asciidoc, line 63 at r4](https://reviewable.io:443/reviews/vaadin/flow-and-components-documentation/11#-L6QIw4JYetvq5PCY6Je:-L6QeT3ywPhmBFnBJ_pe:b-896fix) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/6c18e5e656ac45962fd99c6d1295c32ebfec8cec/migration/1-migrating-v8-v10.asciidoc#L63)):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

> <<5-components#Component Set,Component Sett>>

typo, Component Set
</blockquote></details>

Done.

---

*[migration/5-components.asciidoc, line 50 at r4](https://reviewable.io:443/reviews/vaadin/flow-and-components-documentation/11#-L6QSthK4rdtuMN85W5p:-L6QeMEr4A-FEW5RcTGc:b-v5e55r) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/6c18e5e656ac45962fd99c6d1295c32ebfec8cec/migration/5-components.asciidoc#L50)):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

i  didn't find any page for the java examples of `ordered-layout`, maybe we should ask the vaadin.com team for this. Not a blocker
</blockquote></details>

I've pushed the issue to them, it will appear to them, let it be 404 for now

---

*[migration/5-components.asciidoc, line 206 at r4](https://reviewable.io:443/reviews/vaadin/flow-and-components-documentation/11#-L6QCuwbj7TipBcphmjC:-L6Qf6xIRd-S6Pw3TtLe:b-896fix) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/6c18e5e656ac45962fd99c6d1295c32ebfec8cec/migration/5-components.asciidoc#L206)):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

> (https://github.com/vaadin/flow/issues/2465)[enhancement issue]


https://github.com/vaadin/flow/issues/2465[enhancement issue]
</blockquote></details>

Done.

---

*[migration/7-tools-integrations.asciidoc, line 52 at r4](https://reviewable.io:443/reviews/vaadin/flow-and-components-documentation/11#-L6QHBeKS-DDh_3CcmEf:-L6QfB87-2tI_iy40EDS:b-896fix) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/6c18e5e656ac45962fd99c6d1295c32ebfec8cec/migration/7-tools-integrations.asciidoc#L52)):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

>  <template>

```
this should be `<template>` to be consistent with all the others used in the guide. 
```
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow-and-components-documentation/11)*

**Comment by ZheSun88** [comment]
Reviewed 3 of 3 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/11)*

**Comment by ZheSun88** [comment]
Reviewed 2 of 2 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow-and-components-documentation/11)*

**Pull request merged**
