### PR TITLE
Describe event filtering and debounce

### PR DESCRIPTION
**Pull request by Legioth**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow-and-components-documentation/93)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow-and-components-documentation/93)*

**Comment by denis-anisimov** [comment]
Looks like needs manual rebase. Compilation errors related to `Grid` not touched in this PR.

**Comment by gilberto-torrezan** [comment]
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[documentation/creating-components/tutorial-component-events.asciidoc, line 144 at r1](https://reviewable.io/reviews/vaadin/flow-and-components-documentation/93#-LB-sQrJ8gS5Ws0MIfVd:-LB-sQrJ8gS5Ws0MIfVe:b-1483gr) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/b8a41252f66a528b398ee6ba7863650b7c15c4e8/documentation/creating-components/tutorial-component-events.asciidoc#L144)):*
> ```AsciiDoc
> Some kinds of events are fired very frequently while the user is doing something, like text input events while the user is typing. The rate of sending events to the server can be configured using different `debounce` settings in the `@DomEvent` annotation. Debouncing always requires a `timeout` in milliseconds and one or several phases of a burst for which an event should be sent to the server.
> 
> * Listening for the `LEADING` phase means that an event will be sent to the server at the beginning of a burst, but subsequent events will be dropped until one timeout period has passed without any new events. This may be useful for things like button clicks if you want to prevent accidental double submissions.
> ```

`This may be useful` -> `This is useful` , to be consistent with the `TRAILING` case.

---

*[documentation/creating-components/tutorial-component-events.asciidoc, line 145 at r1](https://reviewable.io/reviews/vaadin/flow-and-components-documentation/93#-LB-sanQA3fwzElwHjhS:-LB-sanQA3fwzElwHjhT:b-h4q8ct) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/b8a41252f66a528b398ee6ba7863650b7c15c4e8/documentation/creating-components/tutorial-component-events.asciidoc#L145)):*
> ```AsciiDoc
> 
> * Listening for the `LEADING` phase means that an event will be sent to the server at the beginning of a burst, but subsequent events will be dropped until one timeout period has passed without any new events. This may be useful for things like button clicks if you want to prevent accidental double submissions.
> * With the `INTERMEDIATE` phase, there will be periodical events to the server while a burst is ongoing. Another event will not be sent to the server until the timeout period has passed since the last event was sent.
> ```

Do you have an example to mention for when this setting would be useful?

---

*[documentation/creating-components/tutorial-component-events.asciidoc, line 148 at r1](https://reviewable.io/reviews/vaadin/flow-and-components-documentation/93#-LB-thM26CiPRdS8wh7E:-LB-thM26CiPRdS8wh7F:b-jg999p) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/b8a41252f66a528b398ee6ba7863650b7c15c4e8/documentation/creating-components/tutorial-component-events.asciidoc#L148)):*
> ```
> You can configure your event to be active for several phases at once, e.g. to both receive an event for the `LEADING` phase immediately when a burst starts but also `INTERMEDIATE` events while the burst goes on.
> ```

I suggest moving this paragraph to after the example, and then create an example for this particular case, showing the annotation with multiple phases.

---

*[documentation/creating-components/tutorial-component-events.asciidoc, line 170 at r1](https://reviewable.io/reviews/vaadin/flow-and-components-documentation/93#-LB-sr8OCVUqpBGf6je0:-LB-sr8OCVUqpBGf6je1:b-3b504w) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/b8a41252f66a528b398ee6ba7863650b7c15c4e8/documentation/creating-components/tutorial-component-events.asciidoc#L170)):*
> ```AsciiDoc
> ----
> 
> If both `filter` and `debounce` are configured at once, only events that pass the filter are considered when determining whether a burst has ended.
> ```

I suggest adding this sentence as a `[NOTE]`, to give more emphasis to it.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow-and-components-documentation/93)*

**Comment by Legioth** [comment]
Review status: 1 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[documentation/creating-components/tutorial-component-events.asciidoc, line 144 at r1](https://reviewable.io/reviews/vaadin/flow-and-components-documentation/93#-LB-sQrJ8gS5Ws0MIfVd:-LB0P5mb9BEa24isP3GP:b-mc7ctc) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/067e230d126f9333c3064d01759c08a4aa8bd2e2/documentation/creating-components/tutorial-component-events.asciidoc#L144)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

`This may be useful` -> `This is useful` , to be consistent with the `TRAILING` case.
</blockquote></details>

I'll do the opposite.

---

*[documentation/creating-components/tutorial-component-events.asciidoc, line 145 at r1](https://reviewable.io/reviews/vaadin/flow-and-components-documentation/93#-LB-sanQA3fwzElwHjhS:-LB0Q37b0yY7sbjed8_t:b-896fix) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/067e230d126f9333c3064d01759c08a4aa8bd2e2/documentation/creating-components/tutorial-component-events.asciidoc#L145)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

Do you have an example to mention for when this setting would be useful?
</blockquote></details>

Done.

---

*[documentation/creating-components/tutorial-component-events.asciidoc, line 148 at r1](https://reviewable.io/reviews/vaadin/flow-and-components-documentation/93#-LB-thM26CiPRdS8wh7E:-LB0RjXTAuRl44-ELJv6:b-896fix) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/067e230d126f9333c3064d01759c08a4aa8bd2e2/documentation/creating-components/tutorial-component-events.asciidoc#L148)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

> ```
> You can configure your event to be active for several phases at once, e.g. to both receive an event for the `LEADING` phase immediately when a burst starts but also `INTERMEDIATE` events while the burst goes on.
> ```

I suggest moving this paragraph to after the example, and then create an example for this particular case, showing the annotation with multiple phases.
</blockquote></details>

Done.

---

*[documentation/creating-components/tutorial-component-events.asciidoc, line 170 at r1](https://reviewable.io/reviews/vaadin/flow-and-components-documentation/93#-LB-sr8OCVUqpBGf6je0:-LB0SB9r0hbJgAK0wbON:b-896fix) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/067e230d126f9333c3064d01759c08a4aa8bd2e2/documentation/creating-components/tutorial-component-events.asciidoc#L170)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

I suggest adding this sentence as a `[NOTE]`, to give more emphasis to it.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow-and-components-documentation/93)*

**Comment by gilberto-torrezan** [comment]
:lgtm:

---

Reviewed 1 of 3 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow-and-components-documentation/93#-:-LB0WhyA6UbLqNwpVgXO:bnfp4nl)*

**Pull request merged**
