### PR TITLE
Update tutorial-webcomponent-compatibility.asciidoc

### PR DESCRIPTION
**Pull request by ruthstocks**
- First edit

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow-and-components-documentation/690)

### CODE REVIEW

**Comment by alejandro-du** [comment]
___
*[documentation/embedding-flow-applications/tutorial-webcomponent-compatibility.asciidoc, line 2 at r1](https://reviewable.io/reviews/vaadin/flow-and-components-documentation/690#-LmJG5A00Zr6R_mhlNvN:-LmJG5A00Zr6R_mhlNvO:b-7khva) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/8197fe6e8088b22c014226878192fbfa087ccaae/documentation/embedding-flow-applications/tutorial-webcomponent-compatibility.asciidoc#L2)):*
> ```AsciiDoc
> ---
> title: Importing Embedded Applications in Compatibility and Production Mode 
> ```

@ruthstocks Cannot we use "Embedding"? Importing sounds a bit confusing.

**Comment by ruthstocks** [comment]
> _[documentation/embedding-flow-applications/tutorial-webcomponent-compatibility.asciidoc, line 2 at r1](https://reviewable.io/reviews/vaadin/flow-and-components-documentation/690#-LmJG5A00Zr6R_mhlNvN:-LmJG5A00Zr6R_mhlNvO:b-7khva) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/8197fe6e8088b22c014226878192fbfa087ccaae/documentation/embedding-flow-applications/tutorial-webcomponent-compatibility.asciidoc#L2)):_
> 
> > ```
> > ---
> > title: Importing Embedded Applications in Compatibility and Production Mode 
> > ```
> 
> @ruthstocks Cannot we use "Embedding"? Importing sounds a bit confusing.

Done.

**Comment by alejandro-du** [comment]
___
*[documentation/embedding-flow-applications/tutorial-webcomponent-compatibility.asciidoc, line 11 at r2](https://reviewable.io/reviews/vaadin/flow-and-components-documentation/690#-LmJo4yl5F2F4B0L9Kj6:-LmJo4yl5F2F4B0L9Kj7:b1nbbnz) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/c6fd56f1b63304ed29675c4058af51f20b11180b/documentation/embedding-flow-applications/tutorial-webcomponent-compatibility.asciidoc#L11)):*
> ```AsciiDoc
> == Compatibility Mode
> 
> When importing embedded applications in compatibility mode, the following differences to development mode need to be taken into account: 
> ```

@ruthstocks same here and any other occurrences in this doc.

**Comment by ruthstocks** [comment]
> _[documentation/embedding-flow-applications/tutorial-webcomponent-compatibility.asciidoc, line 11 at r2](https://reviewable.io/reviews/vaadin/flow-and-components-documentation/690#-LmJo4yl5F2F4B0L9Kj6:-LmJo4yl5F2F4B0L9Kj7:b1nbbnz) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/c6fd56f1b63304ed29675c4058af51f20b11180b/documentation/embedding-flow-applications/tutorial-webcomponent-compatibility.asciidoc#L11)):_
> 
> > ```
> > == Compatibility Mode
> > 
> > When importing embedded applications in compatibility mode, the following differences to development mode need to be taken into account: 
> > ```
> 
> @ruthstocks same here and any other occurrences in this doc.

Done. Sorry.

**Pull request merged**
