### PR TITLE
Update documentation about theme variants, and Lumo.DARK

### PR DESCRIPTION
**Pull request by gilberto-torrezan**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow-and-components-documentation/81)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[documentation/src/main/java/com/vaadin/flow/tutorial/theme/ComponentTheme.java, line 57 at r1](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/81#-LAN6kBM0YdA_RdZ_pa1:-LAN6kBM0YdA_RdZ_pa2:bff2zjb) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/3d30a93ffe81276bd1dc18cf47b9aa24bf1a64f2/documentation/src/main/java/com/vaadin/flow/tutorial/theme/ComponentTheme.java#L57)):*
<details><summary><i alt="summary">Quoted 7 lines of code…</i></summary>

> ```
>             Map<String, String> map = new HashMap<>();
>             if ("dark".equals(variant)) {
>                 // the <body> element will have the "theme" attribute set to
>                 // "dark" when the dark variant is used
>                 map.put("theme", "dark");
>             }
>             return map;
> ```
</details>


So it's either one key-value map or an empty ?

May be return `Collections.singletonMap` in one case and `Collections.emptyMap` in another ?

---

*[documentation/theme/using-component-themes.asciidoc, line 119 at r1](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/81#-LAN7RM803Ew2_YeUPCx:-LAN7RM803Ew2_YeUPCy:b-rd12km) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/3d30a93ffe81276bd1dc18cf47b9aa24bf1a64f2/documentation/theme/using-component-themes.asciidoc#L119)):*
> ```
> contrast primary"
> ```

What's the `contrast` and the `primary` value here ?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/81)*

**Comment by gilberto-torrezan** [comment]
Review status: 1 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[documentation/src/main/java/com/vaadin/flow/tutorial/theme/ComponentTheme.java, line 57 at r1](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/81#-LAN6kBM0YdA_RdZ_pa1:-LANBK9T6PTfztH7XdHB:b-896fix) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/3d30a93ffe81276bd1dc18cf47b9aa24bf1a64f2/documentation/src/main/java/com/vaadin/flow/tutorial/theme/ComponentTheme.java#L57)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> ```
>             Map<String, String> map = new HashMap<>();
>             if ("dark".equals(variant)) {
>                 // the <body> element will have the "theme" attribute set to
>                 // "dark" when the dark variant is used
>                 map.put("theme", "dark");
>             }
>             return map;
> ```

So it's either one key-value map or an empty ?

May be return `Collections.singletonMap` in one case and `Collections.emptyMap` in another ?
</blockquote></details>

Done.

---

*[documentation/theme/using-component-themes.asciidoc, line 119 at r1](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/81#-LAN7RM803Ew2_YeUPCx:-LANAwueD5SlX2Ms4zda:b-p9p7lj) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/3d30a93ffe81276bd1dc18cf47b9aa24bf1a64f2/documentation/theme/using-component-themes.asciidoc#L119)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> ```
> contrast primary"
> ```

What's the `contrast` and the `primary` value here ?
</blockquote></details>

Variants supported by the Button component, as described in the link bellow. The idea is to show how it works and not all possible configurations (since it is described elsewhere).
Added a link for the button just in case.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/81)*

**Comment by denis-anisimov** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[documentation/theme/using-component-themes.asciidoc, line 119 at r1](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/81#-LAN7RM803Ew2_YeUPCx:-LANEHa--v8XfE4IcYr7:bzckcjz) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/3d30a93ffe81276bd1dc18cf47b9aa24bf1a64f2/documentation/theme/using-component-themes.asciidoc#L119)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

Variants supported by the Button component, as described in the link bellow. The idea is to show how it works and not all possible configurations (since it is described elsewhere).
Added a link for the button just in case.
</blockquote></details>

I'm too lazy to go by links.
I think the explanation what  are the `contrast` and the `primary` should be clarified right here.
Otherwise it's not clear at all.

This is tutorial about theming as a whole. But it requires some knowledge about `Button`(or forces me to go and learn it). I think it's not good. The `Button` should be here as just an example without requirement to know anything about it.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/81)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[documentation/theme/using-component-themes.asciidoc, line 119 at r1](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/81#-LAN7RM803Ew2_YeUPCx:-LANLJlc94bFiI5JzLdu:b-fa0491) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/3d30a93ffe81276bd1dc18cf47b9aa24bf1a64f2/documentation/theme/using-component-themes.asciidoc#L119)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

Well, we can use any other component. The idea is to show how do you `set the theme attribute`, and I wanted to show something that actually works. I can change it to `setAttribute("theme", "foo") // see what can be set at http:// ...`, but that doesn't bring any value IMO.

I can also remove the code entirely and revert to the old text where only mentions that you can set the `theme`  but doesn't give any code example.

But I refuse to copy-paste the entire description of what is supported by the component, because it will go out-of-sync pretty fast and it will be a nightmare to maintain.
</blockquote></details>

No need to copy-paste entire description.
You are using magic strings here: `contrast primary`.

I don't understand what there are (as I said : they are magic).

Just make a note here under the code that those two strings are theme variants for `Button` .
That's it.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/81)*

**Comment by gilberto-torrezan** [comment]
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[documentation/theme/using-component-themes.asciidoc, line 119 at r1](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/81#-LAN7RM803Ew2_YeUPCx:-LANNbrk7-or7iIjr772:b-wmjha5) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/3d30a93ffe81276bd1dc18cf47b9aa24bf1a64f2/documentation/theme/using-component-themes.asciidoc#L119)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

No need to copy-paste entire description.
You are using magic strings here: `contrast primary`.

I don't understand what there are (as I said : they are magic).

Just make a note here under the code that those two strings are theme variants for `Button` .
That's it.
</blockquote></details>

Pushed new attempt.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/81)*

**Comment by denis-anisimov** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/81#-:-LANPYT60vMZA7nELKJO:bnfp4nl)*

**Pull request merged**
