### PR TITLE
Migrate Flow tutorial to vaadin-learning-center

### PR DESCRIPTION
**Pull request by Haprog**
The Flow tutorial source has been migrated to https://github.com/vaadin-learning-center/learning-content/tree/development/tutorials/getting-started-with-flow
which is displayed at https://vaadin.com/tutorials/getting-started-with-flow

Removed the tutorial text contents from this repository so that it will disappear from https://vaadin.com/docs
Updated links in here to link to the new location of this tutorial.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow-and-components-documentation/364)

### CODE REVIEW

**Comment by mstahv** [comment]
@pleku We should land this patch. Currently it is quite weird that redirects already push to the "learning center" and still, though /docs navigation you can end up to the same tutorial under /docs.

@marcushellberg Have you already moved the actual source code of the tutorial app to the new place? If so, then I guess we could remove that source code from here too.

**Comment by Haprog** [comment]
@mstahv The newer tutorial still has a link "[download the final application](https://github.com/vaadin/flow-and-components-documentation/tree/master/tutorial-getting-started)" which links to `flow-and-components-documentation/tutorial-getting-started/` in this repository. So we can't remote the example app code from here at least yet.

**Comment by mstahv** [comment]
I wouldn't worry about that  as it is already currently practically useless. Developers can't download it from github (except by downloading the whole repo from the top level). It is probably very confusing and should be removed altogether unless done somehow better. 

Previously we used to have a links to start from any of the sections and I'd really hope to get something similar back at some point. Ping @marcushellberg

**Comment by Haprog** [comment]
> > ```
> > https://vaadin.com/tutorials/getting-started-with-flow
> > ```
> 
> Should this be an inside site link instead ? (not blocking)

Not exactly sure what you mean with "inside site link" here. I think these links that go outside the current repository make sense to be absolute URLs so they also work when you're (pre)viewing the file in e.g. GitHub.

When hosted at vaadin.com/docs it seems that currently only all relative links get the `router-link` attribute, but we could extend this so that we can set e.g. `[.router-link]` role for the link in the source and inject the `router-link` attribute also for links contained in an element with class `router-link`. But that's just a small UX enhancement since I don't think we have many of these in Docs right now.

**Comment by mstahv** [comment]
The "download" link is actually super confusing ATM as it points out to a project that has classes like this: https://github.com/vaadin/flow-and-components-documentation/blob/master/tutorial-getting-started/src/main/java/com/vaadin/starter/skeleton/TutorialGetStartedThirdPart.java 

It should be removed ASAP and added back in some sane way later.

**Pull request merged**
