### PR TITLE
The app fails in section 6 without some changes

### PR DESCRIPTION
**Pull request by nikove**
In section 6, checking for changes will cause all kinds of problems unless the setCustomer(null); is commented out. 

I did not add a section where the reader needs to uncomment this, with the assumption that this is clear.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow-and-components-documentation/114)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[documentation/introduction/tutorial-get-started.asciidoc, line 579 at r1](https://reviewable.io/reviews/vaadin/flow-and-components-documentation/114#-LBqjg3A-1dOPoqcRWke:-LBqjg3A-1dOPoqcRWkf:b-sq42mn) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/ab610e7f77a6155f2469a244f82655ea18b0c567/documentation/introduction/tutorial-get-started.asciidoc#L579)):*
> ```
> To do so, make sure to comment out the following in the [classname]#CustomerForm# in order to avoid errors.
> ```

I don't think this sentence relates to the previous one.
The main idea there is to show the code even if it contains errors at the moment.
The added sentence is about fixing the compilation error.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow-and-components-documentation/114)*

**Comment by nikove** [comment]
Problem is that the tutorial specifically gets the reader to run the application at this point. It will fail, and we need to fix this.

So the following options exist:
 - update the previous section to omit using setCustomer which doesn't exist at this point. We then need to add it at a later point back to the tutorial
 - add an empty method at this point
 - comment it out

I felt that commenting it out was the easiest solution here as we are 'temporarily' trying it out.

What do you recommend? I am not that familiar with our documentation approach.

**Comment by denis-anisimov** [comment]
There is no any approach.
Any way would work but the added sentence is a bit out of the context from my point of view.
You suggest to make the code make compilable (and it's OK) but it happens suddenly. I don't see any mention of 
compilable application in previous (nearest) text.
So the sentence is out of the context.

So I would either suggest: 
- Explicitly mention that "if you want to get compilable application right away please comment the method call".
- Or just comment this method call in the code and mention it somehow.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow-and-components-documentation/114#-:-LBt4wOW2RdZsV7G4Nci:b-lcl9fu)*

**Comment by nikove** [comment]
Discussion with @Legioth - option 1 and 2 above are both reasonable. I will go for option 1, and bundle the addition of setCustomer(null); with the creation of the setCustomer method.

**Comment by denis-anisimov** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[documentation/introduction/tutorial-get-started.asciidoc, line 672 at r2](https://reviewable.io/reviews/vaadin/flow-and-components-documentation/114#-LBtAf_f3jzQohBezeHM:-LBtAf_f3jzQohBezeHN:b-99nt6s) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/5a0855f0153a8669bb713526ab02f9114f555ee4/documentation/introduction/tutorial-get-started.asciidoc#L672)):*
> ```
> To finish off the setter method
> ```

And again here: I don't see in the context around _the setter method_. Which method you are referring to ?

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow-and-components-documentation/114)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[documentation/introduction/tutorial-get-started.asciidoc, line 672 at r2](https://reviewable.io/reviews/vaadin/flow-and-components-documentation/114#-LBtAf_f3jzQohBezeHM:-LBtosi4-K8BYgZBF0Rc:b1x2dlt) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/5a0855f0153a8669bb713526ab02f9114f555ee4/documentation/introduction/tutorial-get-started.asciidoc#L672)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> ```
> To finish off the setter method
> ```

And again here: I don't see in the context around _the setter method_. Which method you are referring to ?
</blockquote></details>

Wel......
I still think that the context is a bit lost at this point.
In the `reviewable` it's even worse (since it shows only several line around) but also in the text there are : paragraph this doesn't mention the original setter and a tip which also is totally out of the context.
I would recommend to use _the `setCustomer` setter method_ here instead to explicitly show which exactly setter you refer to.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow-and-components-documentation/114)*

**Comment by denis-anisimov** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[documentation/introduction/tutorial-get-started.asciidoc, line 672 at r4](https://reviewable.io/reviews/vaadin/flow-and-components-documentation/114#-LCSRACTD00oTXhsWbQ4:-LCSRACTD00oTXhsWbQ5:b-ix0vkf) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/03bf5158c105ecc413e213d5dd61bcb57950bb3e/documentation/introduction/tutorial-get-started.asciidoc#L672)):*
> ```
> setCustomer
> ```

Please add back ticks "``" around of the `setCustomer` to emphasize it as a method name.

Also please press the button `Done` or let me somehow note that this is fixed (write a comment or whatever) otherwise I don't get any notification about this PR and it will stuck here forever (or until someone says me to go and check it).

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow-and-components-documentation/114)*

**Comment by denis-anisimov** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow-and-components-documentation/114)*

**Comment by pekam** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[documentation/introduction/tutorial-get-started.asciidoc, line 672 at r2](https://reviewable.io/reviews/vaadin/flow-and-components-documentation/114#-LBtAf_f3jzQohBezeHM:-LD5i6YO8vymppREs-c6:b-pwaz1e) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/d6bc90e126a72f54849847baecda383c9a35b136/documentation/introduction/tutorial-get-started.asciidoc#L672)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Wel......
I still think that the context is a bit lost at this point.
In the `reviewable` it's even worse (since it shows only several line around) but also in the text there are : paragraph this doesn't mention the original setter and a tip which also is totally out of the context.
I would recommend to use _the `setCustomer` setter method_ here instead to explicitly show which exactly setter you refer to.
</blockquote></details>

I think @nikove already resolved this one even though not noted here in the review comments.

---

*[documentation/introduction/tutorial-get-started.asciidoc, line 672 at r4](https://reviewable.io/reviews/vaadin/flow-and-components-documentation/114#-LCSRACTD00oTXhsWbQ4:-LD5iUjI3so-45ehiEL9:b-896fix) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/f9fa2e699d9eeaa56082c1e5ce362491aca79d9e/documentation/introduction/tutorial-get-started.asciidoc#L672)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> ```
> setCustomer
> ```

Please add back ticks "``" around of the `setCustomer` to emphasize it as a method name.

Also please press the button `Done` or let me somehow note that this is fixed (write a comment or whatever) otherwise I don't get any notification about this PR and it will stuck here forever (or until someone says me to go and check it).
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow-and-components-documentation/114)*

**Comment by denis-anisimov** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow-and-components-documentation/114#-:-LD5lAV523MBFNrxnRXO:bnfp4nl)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[documentation/introduction/tutorial-get-started.asciidoc, line 672 at r2](https://reviewable.io/reviews/vaadin/flow-and-components-documentation/114#-LBtAf_f3jzQohBezeHM:-LD5lFFn9xW64IxapEkN:b-bbfr55) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/d6bc90e126a72f54849847baecda383c9a35b136/documentation/introduction/tutorial-get-started.asciidoc#L672)):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

I think @nikove already resolved this one even though not noted here in the review comments.
</blockquote></details>

you are blocking this.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow-and-components-documentation/114)*

**Comment by pekam** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[documentation/introduction/tutorial-get-started.asciidoc, line 672 at r2](https://reviewable.io/reviews/vaadin/flow-and-components-documentation/114#-LBtAf_f3jzQohBezeHM:-LD5n2sU7loKOf-EPoke:bb7m3jc) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/d6bc90e126a72f54849847baecda383c9a35b136/documentation/introduction/tutorial-get-started.asciidoc#L672)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

you are blocking this.
</blockquote></details>

oops

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow-and-components-documentation/114)*

**Pull request merged**
