### PR TITLE
Grammar and style updates

### PR DESCRIPTION
**Pull request by Mikaelsu**
Missing semicolons and prepositions etc.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow-and-components-documentation/978)

### CODE REVIEW

**Review by torok-peter — DISMISSED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vaadin/flow-and-components-documentation/978#-:-LydAsHH3A1-t-2WDHZS:bnfp4nl)* status: :shipit: complete! all discussions resolved, 1 of 1 LGTMs obtained

**Comment by jouni** [comment]
@magi42, could you pick these changes to master instead, if they are still applicable?

**Comment by magi42** [comment]
Master or V14-next? (And to V14.1 and V14.2 from there.)

**Comment by jouni** [comment]
To me it looks like these changes apply to V15 and onwards as well. So I would pick them to master first, then from there to all major versions.

**Comment by pleku** [comment]
Since this was targeting an old not-supported branch and retargeting master causes conflicts, closing the PR.

Should be retargeted to `master`.

**Pull request closed without merging**
