### PR TITLE
Add push documentation

### PR DESCRIPTION
**Pull request by Legioth**
Based on corresponding documentation for FW8.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow-and-components-documentation/20)

### CODE REVIEW

**Comment by caalador** [comment]
Reviewed 5 of 6 files at r1.
Review status: 5 of 6 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[advanced/tutorial-push-broadcaster.asciidoc, line 10 at r1](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/20#-L5wiHL5AW-Hvb8mvUcT:-L5wiHL5AW-Hvb8mvUcU:b-k2cjfl) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/fc06f02650a3e8dc6b7d73426523326ea6b461d4/advanced/tutorial-push-broadcaster.asciidoc#L10)):*
> ```AsciiDoc
> 
> [[push.broadcaster]]
> = Creating Collaborative Views
> ```

Will there be something in this document?

---

*[advanced/tutorial-push-configuration.asciidoc, line 37 at r1](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/20#-L5wioaZ8qX5ReN7-QXC:-L5wioaZ8qX5ReN7-QXD:b-xbe1qo) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/fc06f02650a3e8dc6b7d73426523326ea6b461d4/advanced/tutorial-push-configuration.asciidoc#L37)):*
> `automatic``

one ' too many

---

*[advanced/tutorial-push-configuration.asciidoc, line 40 at r1](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/20#-L5wjDUg-1Pim0iNg2gr:-L5wjDUg-1Pim0iNg2gs:b4kppfp) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/fc06f02650a3e8dc6b7d73426523326ea6b461d4/advanced/tutorial-push-configuration.asciidoc#L40)):*
> `push()

missing the end '

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/20)*

**Comment by Legioth** [comment]
Review status: 5 of 6 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[advanced/tutorial-push-broadcaster.asciidoc, line 10 at r1](https://reviewable.io:443/reviews/vaadin/flow-and-components-documentation/20#-L5wiHL5AW-Hvb8mvUcT:-L5xGbs8qJxKindsn8AX:b-vjzmzf) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/fc06f02650a3e8dc6b7d73426523326ea6b461d4/advanced/tutorial-push-broadcaster.asciidoc#L10)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

Will there be something in this document?
</blockquote></details>

Will be added later, but the skeleton file was accidentally committed

---

*[advanced/tutorial-push-configuration.asciidoc, line 37 at r1](https://reviewable.io:443/reviews/vaadin/flow-and-components-documentation/20#-L5wioaZ8qX5ReN7-QXC:-L5xH9Av93FqZfvrgu3J:b-896fix) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/fc06f02650a3e8dc6b7d73426523326ea6b461d4/advanced/tutorial-push-configuration.asciidoc#L37)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

> `automatic``

one ' too many
</blockquote></details>

Done.

---

*[advanced/tutorial-push-configuration.asciidoc, line 40 at r1](https://reviewable.io:443/reviews/vaadin/flow-and-components-documentation/20#-L5wjDUg-1Pim0iNg2gr:-L5xH9T09rwzuMMQbl70:b-896fix) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/fc06f02650a3e8dc6b7d73426523326ea6b461d4/advanced/tutorial-push-configuration.asciidoc#L40)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

> `push()

missing the end '
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow-and-components-documentation/20)*

**Comment by Legioth** [comment]
Review status: 4 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[advanced/tutorial-push-broadcaster.asciidoc, line 10 at r1](https://reviewable.io:443/reviews/vaadin/flow-and-components-documentation/20#-L5wiHL5AW-Hvb8mvUcT:-L5xHJZpl0FTnULlWCWY:bp7n0g3) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/fc06f02650a3e8dc6b7d73426523326ea6b461d4/advanced/tutorial-push-broadcaster.asciidoc#L10)):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

Will be added later, but the skeleton file was accidentally committed
</blockquote></details>

later = separate PR

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow-and-components-documentation/20)*

**Comment by caalador** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow-and-components-documentation/20)*

**Comment by caalador** [comment]
Reviewed 6 of 6 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow-and-components-documentation/20)*

**Comment by pleku** [comment]
Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow-and-components-documentation/20)*

**Pull request merged**
