### PR TITLE
Update skeleton -> project base

### PR DESCRIPTION
**Pull request by pleku**
Pending new vaadin.com/start design to be launched

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow-and-components-documentation/16)

### CODE REVIEW

**Comment by pleku** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow-and-components-documentation/16#-L5Ow78U5X7-MRmzV2qQ:-L5Ow78U5X7-MRmzV2qR:bhuftxf) (no related file):*
Blocked until site is updated

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow-and-components-documentation/16)*

**Comment by denis-anisimov** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow-and-components-documentation/16)*

**Comment by caalador** [comment]
Found 2 problems with documentation
1. Tutorial introduction/tutorial-get-started.asciidoc contains the code line '        Button button = new Button("Click me", event -> template.setValue("Clicked!"));' that is not present in any of the corresponding code files
2. Tutorial introduction/tutorial-get-started.asciidoc contains the code line '        setClassName("main-layout");' that is not present in any of the corresponding code files

**Comment by ZheSun88** [comment]
Now, the patch is ready to go,  Only needs a review and @pleku to unblock his comment below. 

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow-and-components-documentation/16#-:-L6zNuFddLDUcQeV0QUY:b-wiz9td)*

**Comment by gilberto-torrezan** [comment]
Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/java/com/vaadin/flow/tutorial/getstarted/MainView.java, line 95 at r5](https://reviewable.io:443/reviews/vaadin/flow-and-components-documentation/16#-L73V1GvCTvBSnKOFqe5:-L73V1GvCTvBSnKOFqe6:br1mq2e) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/d0f903c05a7eca1fb3c1e0af78ddb42f3e91d196/src/main/java/com/vaadin/flow/tutorial/getstarted/MainView.java#L95)):*
> ```Java
>                 event -> template.setValue("Clicked!"));
>         add(button, template);
>         setClassName("main-layout");
> ```

Why do we need this class name here? What does it do?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow-and-components-documentation/16)*

**Comment by pleku** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/java/com/vaadin/flow/tutorial/getstarted/MainView.java, line 95 at r5](https://reviewable.io:443/reviews/vaadin/flow-and-components-documentation/16#-L73V1GvCTvBSnKOFqe5:-L73oheGvMPYgL_UMMfF:b-k9y12f) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/d0f903c05a7eca1fb3c1e0af78ddb42f3e91d196/src/main/java/com/vaadin/flow/tutorial/getstarted/MainView.java#L95)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

Why do we need this class name here? What does it do?
</blockquote></details>

I don't recall anymore, but is aligned with the best practices that "you should name your things". This is because later on (or whenever necessary) you can apply theming more easily since. Also it makes it easier to debug and see how the DOM is actually generated.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow-and-components-documentation/16)*

**Pull request merged**
