### PR TITLE
Update tutorial-webcomponent-intro.asciidoc

### PR DESCRIPTION
**Pull request by ruthstocks**
- First major edit

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow-and-components-documentation/682)

### CODE REVIEW

**Comment by alejandro-du** [comment]
@ruthstocks, it seems this doc was changed after your editorial work. Can you take a look at it again?

**Comment by alejandro-du** [comment]
___
*[documentation/embedding-flow-applications/tutorial-webcomponent-intro.asciidoc, line 9 at r3](https://reviewable.io/reviews/vaadin/flow-and-components-documentation/682#-LmPSEvg0tKNKpX2jvYz:-LmPSEvg0tKNKpX2jvZ-:b-teyjlc) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/54e6d0a2162493142ec18c3e73240c9cf85ea303/documentation/embedding-flow-applications/tutorial-webcomponent-intro.asciidoc#L9)):*
> ```AsciiDoc
> = Introduction to Embedding Applications
> 
> Embeddeding applications is a far better alternative to writing monolithic frontends for your applications. 
> ```

@ruthstocks Please remove "far better".

**Comment by ruthstocks** [comment]
> _[documentation/embedding-flow-applications/tutorial-webcomponent-intro.asciidoc, line 9 at r3](https://reviewable.io/reviews/vaadin/flow-and-components-documentation/682#-LmPSEvg0tKNKpX2jvYz:-LmPSEvg0tKNKpX2jvZ-:b-teyjlc) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/54e6d0a2162493142ec18c3e73240c9cf85ea303/documentation/embedding-flow-applications/tutorial-webcomponent-intro.asciidoc#L9)):_
> 
> > ```
> > = Introduction to Embedding Applications
> > 
> > Embeddeding applications is a far better alternative to writing monolithic frontends for your applications. 
> > ```
> 
> @ruthstocks Please remove "far better".
Done

**Comment by alejandro-du** [comment]
___
*[documentation/embedding-flow-applications/tutorial-webcomponent-intro.asciidoc, line 66 at r4](https://reviewable.io/reviews/vaadin/flow-and-components-documentation/682#-LmPWGht9vkVmglNGz3m:-LmPWGht9vkVmglNGz3n:bq4pbu0) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/b69e97a833d36ad7334bf8711685eba7c69bacef/documentation/embedding-flow-applications/tutorial-webcomponent-intro.asciidoc#L66)):*
> ```AsciiDoc
> *Example*: Using the embedded component tag.
> +
> [source, html]
> ```

@ruth this is breaking the build. Please change to inline code formatting.

**Comment by alejandro-du** [comment]
___
*[documentation/embedding-flow-applications/tutorial-webcomponent-intro.asciidoc, line 54 at r4](https://reviewable.io/reviews/vaadin/flow-and-components-documentation/682#-LmPWaFB7Loa-WnaTaDf:-LmPWaFB7Loa-WnaTaDg:bq4pbu0) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/b69e97a833d36ad7334bf8711685eba7c69bacef/documentation/embedding-flow-applications/tutorial-webcomponent-intro.asciidoc#L54)):*
> ```AsciiDoc
> *Example*: Importing `my-component.js`.
> +
> [source, html]
> ```

@ruth this is breaking the build. Please change to inline code formatting.

**Comment by ruthstocks** [comment]
> _[documentation/embedding-flow-applications/tutorial-webcomponent-intro.asciidoc, line 66 at r4](https://reviewable.io/reviews/vaadin/flow-and-components-documentation/682#-LmPWGht9vkVmglNGz3m:-LmPWGht9vkVmglNGz3n:bq4pbu0) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/b69e97a833d36ad7334bf8711685eba7c69bacef/documentation/embedding-flow-applications/tutorial-webcomponent-intro.asciidoc#L66)):_
> 
> > ```
> > *Example*: Using the embedded component tag.
> > +
> > [source, html]
> > ```
> 
> @ruth this is breaking the build. Please change to inline code formatting.

Done

**Comment by ruthstocks** [comment]
> > _[documentation/embedding-flow-applications/tutorial-webcomponent-intro.asciidoc, line 66 at r4](https://reviewable.io/reviews/vaadin/flow-and-components-documentation/682#-LmPWGht9vkVmglNGz3m:-LmPWGht9vkVmglNGz3n:bq4pbu0) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/b69e97a833d36ad7334bf8711685eba7c69bacef/documentation/embedding-flow-applications/tutorial-webcomponent-intro.asciidoc#L66)):_
> > > ```
> > > *Example*: Using the embedded component tag.
> > > +
> > > [source, html]
> > > ```
> > 
> > 
> > @ruth this is breaking the build. Please change to inline code formatting.
> 
> Done



> _[documentation/embedding-flow-applications/tutorial-webcomponent-intro.asciidoc, line 54 at r4](https://reviewable.io/reviews/vaadin/flow-and-components-documentation/682#-LmPWaFB7Loa-WnaTaDf:-LmPWaFB7Loa-WnaTaDg:bq4pbu0) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/b69e97a833d36ad7334bf8711685eba7c69bacef/documentation/embedding-flow-applications/tutorial-webcomponent-intro.asciidoc#L54)):_
> 
> > ```
> > *Example*: Importing `my-component.js`.
> > +
> > [source, html]
> > ```
> 
> @ruth this is breaking the build. Please change to inline code formatting.

Done

**Pull request merged**
