### PR TITLE
Add documentation on running productionMode.

### PR DESCRIPTION
**Pull request by caalador**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow-and-components-documentation/92)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow-and-components-documentation/92#-:-LAwa_TP4Vs3SLcyN4eo:bnfp4nl)*

**Comment by Artur-** [comment]
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[documentation/production/tutorial-production-mode-basic.asciidoc, line 15 at r1](https://reviewable.io/reviews/vaadin/flow-and-components-documentation/92#-LAwfiZ-8fO1QQAgT6kX:-LAwfiZ-8fO1QQAgT6kY:b-ag0uf4) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/25b68e68d6f61d143de1d4032c20a4bb6f84d595/documentation/production/tutorial-production-mode-basic.asciidoc#L15)):*
> ```AsciiDoc
> To get your application prepped for production you want to add the `flow-maven-plugin` into the pom.xml
> 
> If not present add the vaadin-prereleases plugin repository:
> ```

This is only relevant before 1.0.0, maybe rather as a NOTE or delete?

---

*[documentation/production/tutorial-production-mode-basic.asciidoc, line 43 at r1](https://reviewable.io/reviews/vaadin/flow-and-components-documentation/92#-LAwfqBB6P4qF3qaC7mt:-LAwfqBB6P4qF3qaC7mu:bdk7ku9) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/25b68e68d6f61d143de1d4032c20a4bb6f84d595/documentation/production/tutorial-production-mode-basic.asciidoc#L43)):*
> ```AsciiDoc
> 
>         <properties>
>             <transpilation.output>${project.build.directory}/build</transpilation.output>
> ```

Why is this needed?

---

*[documentation/production/tutorial-production-mode-basic.asciidoc, line 67 at r1](https://reviewable.io/reviews/vaadin/flow-and-components-documentation/92#-LAwfrnD8UpMZhFxnYiL:-LAwfrnD8UpMZhFxnYiM:bdk7ku9) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/25b68e68d6f61d143de1d4032c20a4bb6f84d595/documentation/production/tutorial-production-mode-basic.asciidoc#L67)):*
> ```AsciiDoc
>                             </goals>
>                             <configuration>
>                                 <transpileOutputDirectory>${transpilation.output}</transpileOutputDirectory>
> ```

Why is this needed?

---

*[documentation/production/tutorial-production-mode-basic.asciidoc, line 76 at r1](https://reviewable.io/reviews/vaadin/flow-and-components-documentation/92#-LAwfv-H9sop8WwsK8sp:-LAwfv-H9sop8WwsK8sq:bdk7ku9) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/25b68e68d6f61d143de1d4032c20a4bb6f84d595/documentation/production/tutorial-production-mode-basic.asciidoc#L76)):*
> ```AsciiDoc
>                     <groupId>org.apache.maven.plugins</groupId>
>                     <artifactId>maven-war-plugin</artifactId>
>                     <version>${maven.war.plugin.version}</version>
> ```

Why is this needed?

---

*[documentation/production/tutorial-production-mode-basic.asciidoc, line 99 at r1](https://reviewable.io/reviews/vaadin/flow-and-components-documentation/92#-LAwfwWu7y2dLP7Z3D3d:-LAwfwWu7y2dLP7Z3D3e:bdk7ku9) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/25b68e68d6f61d143de1d4032c20a4bb6f84d595/documentation/production/tutorial-production-mode-basic.asciidoc#L99)):*
> ```AsciiDoc
>                         <webAppConfig>
>                             <resourceBases>
>                                 <resourceBase>${transpilation.output}</resourceBase>
> ```

Why is this needed?

---

*[documentation/production/tutorial-production-mode-basic.asciidoc, line 113 at r1](https://reviewable.io/reviews/vaadin/flow-and-components-documentation/92#-LAwfyhCDOxJh31WlocM:-LAwfyhCDOxJh31WlocN:bf8sx67) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/25b68e68d6f61d143de1d4032c20a4bb6f84d595/documentation/production/tutorial-production-mode-basic.asciidoc#L113)):*
> ```AsciiDoc
> The `flow.maven.plugin.version` should be a version that is compatible with the used platform.
> 
> After this all that is needed is to run `mvn clean package -Dvaadin.productionMode`.
> ```

It's confusing to use the same system property here, why not just `-Pproduction` (and rename the profile to `production`)?

---

*[documentation/production/tutorial-production-mode-basic.asciidoc, line 122 at r1](https://reviewable.io/reviews/vaadin/flow-and-components-documentation/92#-LAwgFZF7wuACQ87yyrv:-LAwgFZF7wuACQ87yyrw:b-rv7coy) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/25b68e68d6f61d143de1d4032c20a4bb6f84d595/documentation/production/tutorial-production-mode-basic.asciidoc#L122)):*
> ```AsciiDoc
> == What is transpilation and bundling
> 
> Transpilation in Flow means converting all ES6 JavaScript to ES5 JavaScript format for older browsers to use.
> ```

Could specifically mention IE11 and Safari 9

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow-and-components-documentation/92)*

**Comment by Artur-** [comment]
Reviewed 1 of 4 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[documentation/production/tutorial-production-mode-advanced.asciidoc, line 13 at r1](https://reviewable.io/reviews/vaadin/flow-and-components-documentation/92#-LAwgcHtEHlF-WjIL82N:-LAwgcHtEHlF-WjIL82O:bqvo3ml) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/25b68e68d6f61d143de1d4032c20a4bb6f84d595/documentation/production/tutorial-production-mode-advanced.asciidoc#L13)):*
> ```AsciiDoc
> == Production mode issues
> 
> ====  After adding the `flow-server-production-mode` dependency the application no longer starts.
> ```

Three `=` is enough?

---

*[documentation/production/tutorial-production-mode-advanced.asciidoc, line 20 at r1](https://reviewable.io/reviews/vaadin/flow-and-components-documentation/92#-LAwghgNDr9vR14_JFc2:-LAwghgNDr9vR14_JFc3:b-jzeack) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/25b68e68d6f61d143de1d4032c20a4bb6f84d595/documentation/production/tutorial-production-mode-advanced.asciidoc#L20)):*
> ```AsciiDoc
> To fix this you should either compile the frontend resources, remove the dependency,
> disable production mode with the servlet parameter `original.frontend.resources=true`
> or by running the application with `mvn jetty:run-exploded`.
> ```

Reading this I get the feelings:
* How do I "compile the frontend resources"?
* Why would "remove the dependency" or "disable production mode" be a solution to get it to run in production mode? (the option does not even really disable production mode, right?)
* Why is the real solution last and not first
* What is the difference between using `run-exploded` and `run-war`, do both work?

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow-and-components-documentation/92)*

**Comment by caalador** [comment]
Review status: 2 of 4 files reviewed at latest revision, 9 unresolved discussions.

---

*[documentation/production/tutorial-production-mode-advanced.asciidoc, line 13 at r1](https://reviewable.io/reviews/vaadin/flow-and-components-documentation/92#-LAwgcHtEHlF-WjIL82N:-LB-VbEU-ZnLA_9zM6Rg:b-896fix) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/25b68e68d6f61d143de1d4032c20a4bb6f84d595/documentation/production/tutorial-production-mode-advanced.asciidoc#L13)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

Three `=` is enough?
</blockquote></details>

Done.

---

*[documentation/production/tutorial-production-mode-basic.asciidoc, line 15 at r1](https://reviewable.io/reviews/vaadin/flow-and-components-documentation/92#-LAwfiZ-8fO1QQAgT6kX:-LAwifPGEqOytx0977KV:b-896fix) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/25b68e68d6f61d143de1d4032c20a4bb6f84d595/documentation/production/tutorial-production-mode-basic.asciidoc#L15)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

This is only relevant before 1.0.0, maybe rather as a NOTE or delete?
</blockquote></details>

Done.

---

*[documentation/production/tutorial-production-mode-basic.asciidoc, line 67 at r1](https://reviewable.io/reviews/vaadin/flow-and-components-documentation/92#-LAwfrnD8UpMZhFxnYiL:-LB-USKU5MT_9mQk1FpS:b-rzpclf) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/25b68e68d6f61d143de1d4032c20a4bb6f84d595/documentation/production/tutorial-production-mode-basic.asciidoc#L67)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

Why is this needed?
</blockquote></details>

Done.
removed

---

*[documentation/production/tutorial-production-mode-basic.asciidoc, line 76 at r1](https://reviewable.io/reviews/vaadin/flow-and-components-documentation/92#-LAwfv-H9sop8WwsK8sp:-LB-URwjAQd1DfzEWRyN:b-2jtrnl) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/25b68e68d6f61d143de1d4032c20a4bb6f84d595/documentation/production/tutorial-production-mode-basic.asciidoc#L76)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

Why is this needed?
</blockquote></details>

Done.
apparently is not specifically needed. removed.

---

*[documentation/production/tutorial-production-mode-basic.asciidoc, line 99 at r1](https://reviewable.io/reviews/vaadin/flow-and-components-documentation/92#-LAwfwWu7y2dLP7Z3D3d:-LB-URNcEPIGCbedWOw-:b-95tvtx) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/25b68e68d6f61d143de1d4032c20a4bb6f84d595/documentation/production/tutorial-production-mode-basic.asciidoc#L99)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

Why is this needed?
</blockquote></details>

Done.
moved to own part explaining that it's wanted for simpler jetty:run functionality when running production mode profile.

---

*[documentation/production/tutorial-production-mode-basic.asciidoc, line 113 at r1](https://reviewable.io/reviews/vaadin/flow-and-components-documentation/92#-LAwfyhCDOxJh31WlocM:-LAwh-dhCDHKRPw1ivXx:b50pp29) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/25b68e68d6f61d143de1d4032c20a4bb6f84d595/documentation/production/tutorial-production-mode-basic.asciidoc#L113)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

It's confusing to use the same system property here, why not just `-Pproduction` (and rename the profile to `production`)?
</blockquote></details>

This was because our project bases by default use the property vaadin.productionMode. Changed.

---

*[documentation/production/tutorial-production-mode-basic.asciidoc, line 122 at r1](https://reviewable.io/reviews/vaadin/flow-and-components-documentation/92#-LAwgFZF7wuACQ87yyrv:-LAwhJNDAN8N7gnByGLz:b-896fix) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/25b68e68d6f61d143de1d4032c20a4bb6f84d595/documentation/production/tutorial-production-mode-basic.asciidoc#L122)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

Could specifically mention IE11 and Safari 9
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow-and-components-documentation/92)*

**Comment by caalador** [comment]
Review status: 2 of 4 files reviewed at latest revision, 9 unresolved discussions.

---

*[documentation/production/tutorial-production-mode-advanced.asciidoc, line 20 at r1](https://reviewable.io/reviews/vaadin/flow-and-components-documentation/92#-LAwghgNDr9vR14_JFc2:-LB-Wyt48voHr0_jvZgf:b-896fix) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/25b68e68d6f61d143de1d4032c20a4bb6f84d595/documentation/production/tutorial-production-mode-advanced.asciidoc#L20)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

Reading this I get the feelings:
* How do I "compile the frontend resources"?
* Why would "remove the dependency" or "disable production mode" be a solution to get it to run in production mode? (the option does not even really disable production mode, right?)
* Why is the real solution last and not first
* What is the difference between using `run-exploded` and `run-war`, do both work?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow-and-components-documentation/92)*

**Comment by caalador** [comment]
Review status: 2 of 4 files reviewed at latest revision, 9 unresolved discussions.

---

*[documentation/production/tutorial-production-mode-basic.asciidoc, line 43 at r1](https://reviewable.io/reviews/vaadin/flow-and-components-documentation/92#-LAwfqBB6P4qF3qaC7mt:-LB-X-Nh1nDUNjg4k9I7:b-hfpv0l) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/25b68e68d6f61d143de1d4032c20a4bb6f84d595/documentation/production/tutorial-production-mode-basic.asciidoc#L43)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

Why is this needed?
</blockquote></details>

removed

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow-and-components-documentation/92)*

**Comment by Artur-** [comment]
Review status: 2 of 4 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[documentation/production/tutorial-production-mode-basic.asciidoc, line 21 at r2](https://reviewable.io/reviews/vaadin/flow-and-components-documentation/92#-LB-ZeMCEQ6lHnYDi968:-LB-ZeMCEQ6lHnYDi969:b-qkhr8k) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/2f8d9bd24ddf932ae0b6726c0e0b3dee61306fda/documentation/production/tutorial-production-mode-basic.asciidoc#L21)):*
> ```AsciiDoc
> <profiles>
>     <profile>
>         <id>productionMode</id>
> ```

Would still name this `production` so you can do `mvn install -Pproduction`. Then the `<activation>` part is also optional

---

*[documentation/production/tutorial-production-mode-basic.asciidoc, line 66 at r2](https://reviewable.io/reviews/vaadin/flow-and-components-documentation/92#-LB-ZBuX9jWxtWR6rZYy:-LB-ZBuX9jWxtWR6rZYz:b-wdx9ka) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/2f8d9bd24ddf932ae0b6726c0e0b3dee61306fda/documentation/production/tutorial-production-mode-basic.asciidoc#L66)):*
> ```AsciiDoc
> The `flow.maven.plugin.version` should be a version that is compatible with the used platform.
> 
> After this all that is needed is to run `mvn clean package -Dvaadin.production`.
> ```

`-Pproduction`?

---

*[documentation/production/tutorial-production-mode-basic.asciidoc, line 88 at r2](https://reviewable.io/reviews/vaadin/flow-and-components-documentation/92#-LB-Zy_B4EsqE4PJpHlK:-LB-Zy_B4EsqE4PJpHlL:br60gp8) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/2f8d9bd24ddf932ae0b6726c0e0b3dee61306fda/documentation/production/tutorial-production-mode-basic.asciidoc#L88)):*
> ```AsciiDoc
> ----
> 
> With this the server can be started with `mvn jetty:run -Dvaadin.production`.
> ```

Should `-Dvaadin.production` here also be `-Pproduction`?

---

*[documentation/production/tutorial-production-mode-basic.asciidoc, line 92 at r2](https://reviewable.io/reviews/vaadin/flow-and-components-documentation/92#-LB-_BpWBn8VHOpA1zyt:-LB-_BpWBn8VHOpA1zyu:b-k56em4) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/2f8d9bd24ddf932ae0b6726c0e0b3dee61306fda/documentation/production/tutorial-production-mode-basic.asciidoc#L92)):*
> ```AsciiDoc
> [NOTE]
> *transpilation.output* by default is `${project.build.directory}/${project.build.finalName}/`,
> but could be defined for the flow-maven-plugin also so that one property is used.
> ```

Not sure what this is trying to tell me

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow-and-components-documentation/92)*

**Comment by ZheSun88** [comment]
:lgtm:

---

Reviewed 2 of 4 files at r1, 1 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow-and-components-documentation/92#-:-LBUOQnzBoJt4N2oIY2A:bnfp4nl)*

**Pull request merged**
