### PR TITLE
Added documentation on styling of Grid

### PR DESCRIPTION
**Pull request by mikotin**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow-and-components-documentation/185)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
You should add the code snippets as a validation files ( java, css). See how it's done in other tutorials.
Otherwise the validation fails.

---

Reviewed 1 of 1 files at r1.
Review status: 2 unresolved discussions, 0 of 1 LGTMs obtained

---

*[documentation/components/tutorial-flow-grid.asciidoc, line 895 at r1](https://reviewable.io/reviews/vaadin/flow-and-components-documentation/185#-LEsqB67Cg5R5m09aCNz:-LEsqB68A3alCO0gKQP_:bwtideq) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/514c96ee0ad0ec948183e458d8b883a56074cba8/documentation/components/tutorial-flow-grid.asciidoc#L895)):*
> ```
> indigates
> ```

typo ?

---

*[documentation/components/tutorial-flow-grid.asciidoc, line 948 at r1](https://reviewable.io/reviews/vaadin/flow-and-components-documentation/185#-LEsqYzk5jcjO_flIyPM:-LEsqYzk5jcjO_flIyPN:b-d0wxhj) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/514c96ee0ad0ec948183e458d8b883a56074cba8/documentation/components/tutorial-flow-grid.asciidoc#L948)):*
> ```AsciiDoc
> This does not only apply in the text-fields of the grid, but - because date-field uses the text-field internally - also
> the date-fields. Now the look and feel of used component - the textfield - is always the same, whether it's directly
> used or wrapped within another component.
> ```

new line

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow-and-components-documentation/185#-:-LEsqaa_CmofIYzMIGrs:b-lq3jd4)*

**Comment by denis-anisimov** [comment]
Reviewed 4 of 4 files at r2.
Review status: 1 unresolved discussion, 0 of 1 LGTMs obtained

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow-and-components-documentation/185)*

**Comment by ZheSun88** [comment]
Review status: 1 unresolved discussion, 0 of 1 LGTMs obtained

---

*[a discussion](https://reviewable.io/reviews/vaadin/flow-and-components-documentation/185#-LFLkj-S67NTbdj3AnN_:-LFLkj-S67NTbdj3AnNa:b-eevkjk) (no related file):*
the build failed because grid cannot find the `addThemeName` method,  should there be a separate PR to implement `hasTheme` to grid, together with a grid a demo?

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow-and-components-documentation/185)*

**Comment by ZheSun88** [comment]
This will start to build after vaadin/vaadin-grid-flow#255

**Pull request merged**
