### PR TITLE
Changed components links

### PR DESCRIPTION
**Pull request by binhbbbb**
I have changed those links to Vaadin Directory links. It's beneficial for the Directory SEO.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow-and-components-documentation/252)

### CODE REVIEW

**Comment by pleku** [comment]
>@pleku Any chance we can change all components link in Vaadin docs to our Vaadin Directory links? The Directory component page has a Github link in it as well. And this benefits Directory SEO a lot.

No we will not, since that will not benefit the users. There is a reason why we have our components in vaadin.com/components/browse instead of just directory.

**Comment by binhbbbb** [comment]
Ah I see, I did not see the Vaadin components link. Yeah, I agree with you. As long as there are no wc.org link in Vaadin then I'm fine :wink:

**Comment by binhbbbb** [comment]
Can you accept the change for `iron-iconset-svg` though?

**Comment by binhbbbb** [comment]
Done!

**Pull request merged**
