### PR TITLE
What is enabled/disabled and how to handle it.

### PR DESCRIPTION
**Pull request by caalador**
Closes vaadin/flow#3812

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow-and-components-documentation/58)

### CODE REVIEW

**Comment by caalador** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[documentation/components/tutorial-component-basic-features.asciidoc, line 95 at r1](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/58#-L9FMkG_9615GIlwNtXX:-L9FQDNqBmKopAgZDn5d:b-jt5ili) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/b058fdd378973073a30cb8fbc0f4d8e61434998d/documentation/components/tutorial-component-basic-features.asciidoc#L95)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> ```
> Disabling user interaction of a component means calling `component.setEnabled(false)` on the server
> which then blocks any interaction from the client to the server for the disabled component and its children.
> ```

There is also visual effect (at least the attribute which I don't remember).
</blockquote></details>

This one is hard. There should be a visual effect, but we can't guarantee anything on the server side as it's up to the client component to handle.

Added sends 'disabled'

---

*[documentation/creating-components/tutorial-component-basic.asciidoc, line 64 at r1](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/58#-L9FN1hlAmQfs88wpauo:-L9FQh1Q76dsuSoB_QsY:b-gaw76o) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/b058fdd378973073a30cb8fbc0f4d8e61434998d/documentation/creating-components/tutorial-component-basic.asciidoc#L64)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> ```
> By default disabling the component will add a `disabled` property to the client element, but this
> can be modified by overriding `HasElement:enabledStateChanged(boolean)` method.
> ```

If I still on the same page then:
- the attribute is set from the `setEnabled` method right away ( no need for `enabledStateChanged`).
- the method `onEnabledStateChanged` updates `disabled` attribute for the _children_ which are `HasEnabled` (and its signature may be different: during a discussion it may accept an event as the argument but I'm not sure what as the final decision).  And this may be overridden. 
</blockquote></details>

Right now it is, but as by my understanding it should be overridable and that is then done in a different method that can be overridden by the component developer for any specific case that he may have.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/58)*

**Comment by denis-anisimov** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[documentation/components/tutorial-component-basic-features.asciidoc, line 95 at r1](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/58#-L9FMkG_9615GIlwNtXX:-L9FT-_m9yeaU8rS2j3l:bespamr) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/b058fdd378973073a30cb8fbc0f4d8e61434998d/documentation/components/tutorial-component-basic-features.asciidoc#L95)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

This one is hard. There should be a visual effect, but we can't guarantee anything on the server side as it's up to the client component to handle.

Added sends 'disabled'
</blockquote></details>

`disabled` is OK.

---

*[documentation/creating-components/tutorial-component-basic.asciidoc, line 64 at r1](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/58#-L9FN1hlAmQfs88wpauo:-L9FTA2x0Q_16I6dWYtz:bsy004b) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/b058fdd378973073a30cb8fbc0f4d8e61434998d/documentation/creating-components/tutorial-component-basic.asciidoc#L64)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

Right now it is, but as by my understanding it should be overridable and that is then done in a different method that can be overridden by the component developer for any specific case that he may have.
</blockquote></details>

I have a strong feeling that this section will need an update in the future.
(even now the method that we have been discussing is `onEnabledStateChanged` vs your  `enabledStateChanged`).
And the issue is that we won't be able to find this collision because there is no any verification.

Would it make sense to add a very simple source code sample that will verify the API?
Then once it's changed compilation will fail.

On the other hand in this case this PR can't be merged until there is API for it (but may be this is good?)

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/58)*

**Comment by caalador** [comment]
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[documentation/creating-components/tutorial-component-basic.asciidoc, line 64 at r1](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/58#-L9FN1hlAmQfs88wpauo:-L9FVyzwDcHwdlL31Ghb:bui4zoh) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/b058fdd378973073a30cb8fbc0f4d8e61434998d/documentation/creating-components/tutorial-component-basic.asciidoc#L64)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

I have a strong feeling that this section will need an update in the future.
(even now the method that we have been discussing is `onEnabledStateChanged` vs your  `enabledStateChanged`).
And the issue is that we won't be able to find this collision because there is no any verification.

Would it make sense to add a very simple source code sample that will verify the API?
Then once it's changed compilation will fail.

On the other hand in this case this PR can't be merged until there is API for it (but may be this is good?)
</blockquote></details>

Could probably be good, but I don't know what I would say/do in the overriding change block.

Also the documentation is how do I see it as working and perhaps give insight to the implementation.
It most likely will need changing and updating and probably should only be merged after the feature is in.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/58)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[documentation/creating-components/tutorial-component-basic.asciidoc, line 64 at r1](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/58#-L9FN1hlAmQfs88wpauo:-L9FeVW96sbXgi50z_YH:b-4o9fxz) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/b058fdd378973073a30cb8fbc0f4d8e61434998d/documentation/creating-components/tutorial-component-basic.asciidoc#L64)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

Could probably be good, but I don't know what I would say/do in the overriding change block.

Also the documentation is how do I see it as working and perhaps give insight to the implementation.
It most likely will need changing and updating and probably should only be merged after the feature is in.
</blockquote></details>

I think you should block this PR by yourself then to prevent accidental merge.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/58)*

**Comment by ZheSun88** [comment]
Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---

*[documentation/src/main/java/com/vaadin/flow/tutorial/creatingcomponents/ComponentBasic.java, line 51 at r4](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/58#-L9yVrlMA4wjmNoWFU-n:-L9yVrlMA4wjmNoWFU-o:bz52j36) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/d6c7a2ebdcaedb83f697b0a0373aa20311e8acb9/documentation/src/main/java/com/vaadin/flow/tutorial/creatingcomponents/ComponentBasic.java#L51)):*
> ```Java
>     }
> 
>     private void setDisabled(boolean disabled) {
> ```

Do these parts need to be shown in the docs? 

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/58)*

**Comment by caalador** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[documentation/src/main/java/com/vaadin/flow/tutorial/creatingcomponents/ComponentBasic.java, line 51 at r4](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/58#-L9yVrlMA4wjmNoWFU-n:-L9y_fYdBdu4WD7NXwHm:bz80azq) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/d6c7a2ebdcaedb83f697b0a0373aa20311e8acb9/documentation/src/main/java/com/vaadin/flow/tutorial/creatingcomponents/ComponentBasic.java#L51)):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

Do these parts need to be shown in the docs? 
</blockquote></details>

No. They are just needed for the code to compile and will bring no extra information.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/58)*

**Comment by ZheSun88** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/58#-:-L9ya0J67lqfNuT2M3A5:bnfp4nl)*

**Pull request merged**
