### PR TITLE
mention routing client side in section routing

### PR DESCRIPTION
**Pull request by ptdatkhtn**
Mention client side routing

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow-and-components-documentation/1034)

### CODE REVIEW

**Comment by ptdatkhtn** [comment]
___
*[documentation/routing/tutorial-mention-routing-client-side.asciidoc, line 10 at r1](https://reviewable.io/reviews/vaadin/flow-and-components-documentation/1034#-Lz0uo1O8LqTbTRJ6iV1:-Lz0x1Rz3RE31jnESKyU:b-896fix) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/1c845576c7939c88e27f8753109e71c174e2f0d0/documentation/routing/tutorial-mention-routing-client-side.asciidoc#L10)):*
<details><summary><i>Previously, haijian-vaadin (Haijian Wang) wrote…</i></summary><blockquote>

> ```
> As a developer, sometimes you just want your application to have server-side view
> or client-side view, but sometimes you also would like to develop your application
> in both.
> ```
As a developer, sometimes you want your application only to have server-side views
or client-side views, but sometimes you also would like to have both.
</blockquote></details>

Done.

**Comment by ptdatkhtn** [comment]
___
*[documentation/routing/tutorial-mention-routing-client-side.asciidoc, line 31 at r1](https://reviewable.io/reviews/vaadin/flow-and-components-documentation/1034#-Lz0uIMbCw9GqOJkYCFm:-Lz0x2_y2i2R2QZrS1be:b-896fix) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/1c845576c7939c88e27f8753109e71c174e2f0d0/documentation/routing/tutorial-mention-routing-client-side.asciidoc#L31)):*
<details><summary><i>Previously, haijian-vaadin (Haijian Wang) wrote…</i></summary><blockquote>

> ```
> allow
> ```
allows
</blockquote></details>

Done.

**Comment by ptdatkhtn** [comment]
___
*[documentation/routing/tutorial-mention-routing-client-side.asciidoc, line 37 at r1](https://reviewable.io/reviews/vaadin/flow-and-components-documentation/1034#-Lz0uEEm09i99vAzw4QK:-Lz0x4JA2lEB5NtNqmtO:b-h0xqwv) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/1c845576c7939c88e27f8753109e71c174e2f0d0/documentation/routing/tutorial-mention-routing-client-side.asciidoc#L37)):*
<details><summary><i>Previously, haijian-vaadin (Haijian Wang) wrote…</i></summary><blockquote>

> ```
> what is Vaadin Router
> ```
what Vaadin Router is
</blockquote></details>

I mentioned Vaadin Router in intro part. Do you think i missing anything?

**Comment by haijian-vaadin** [comment]
___
*[documentation/routing/tutorial-mention-routing-client-side.asciidoc, line 37 at r1](https://reviewable.io/reviews/vaadin/flow-and-components-documentation/1034#-Lz0uEEm09i99vAzw4QK:-Lz0y7ql6POEDl9zPuKZ:bgpbl80) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/1c845576c7939c88e27f8753109e71c174e2f0d0/documentation/routing/tutorial-mention-routing-client-side.asciidoc#L37)):*
<details><summary><i>Previously, ptdatkhtn (Thanh Dat PHAN) wrote…</i></summary><blockquote>

I mentioned Vaadin Router in intro part. Do you think i missing anything? 
</blockquote></details>

I mean, just to reorder the words. what is Vaadin Router -> what Vaaidn Router is

**Pull request merged**
