### PR TITLE
Rewrite web component integration docs

### PR DESCRIPTION
**Pull request by Artur-**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow-and-components-documentation/75)

### CODE REVIEW

**Comment by SomeoneToIgnore** [comment]
Reviewed 31 of 32 files at r1.
Review status: 29 of 30 files reviewed at latest revision, all discussions resolved.

---

*[documentation/src/main/java/com/vaadin/flow/tutorial/webcomponent/ClickEvent.java, line 8 at r1](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/75#-LAHPfu64T2qJNVCobZH:-LAHPfu64T2qJNVCobZI:bnbto7f) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/9ec15567040c80400f68f70a25b29e1daf66062d/documentation/src/main/java/com/vaadin/flow/tutorial/webcomponent/ClickEvent.java#L8)):*
> ```Java
> import com.vaadin.flow.tutorial.annotations.CodeFor;
> 
> @CodeFor("dontcare")
> ```

Please do care, here and everywhere else.
This annotation is the way to check that the code in the tutorial and the file match. 
Without it we just check that some arbitrary file compiles which does not make much sense.

---

*[documentation/src/main/java/com/vaadin/flow/tutorial/webcomponent/IconButton.java, line 29 at r1](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/75#-LAHPFRx0uXP-onpP-eT:-LAHPFRy5wU0mERCONfT:b-41489t) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/9ec15567040c80400f68f70a25b29e1daf66062d/documentation/src/main/java/com/vaadin/flow/tutorial/webcomponent/IconButton.java#L29)):*
> ```Java
>                 "vaadin:" + icon.name().toLowerCase().replace("_", "-"));
>         getElement().appendChild(iconElement);
>         // getElement().appendChild(icon.create().getElement());
> ```

Do users need this?

---

*[documentation/web-components/creating-an-in-project-web-component.asciidoc, line 3 at r1](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/75#-LAHRmqU9JEEGVBmLBOe:-LAHRmqU9JEEGVBmLBOf:b-cf54sb) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/9ec15567040c80400f68f70a25b29e1daf66062d/documentation/web-components/creating-an-in-project-web-component.asciidoc#L3)):*
> ```AsciiDoc
> ---
> title: Creating an In-project Web Component
> order: 20
> ```

Previous tutorials have had sequential numbers, any reason to abandon this practice?

---

*[documentation/web-components/creating-an-in-project-web-component.asciidoc, line 7 at r1](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/75#-LAHS3ff6_uW-J_ZAP7x:-LAHS3ff6_uW-J_ZAP7y:b-ngcer9) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/9ec15567040c80400f68f70a25b29e1daf66062d/documentation/web-components/creating-an-in-project-web-component.asciidoc#L7)):*
> ```
> above
> ```

I don't see anything *above* related to the topic. Moreover, the `"Integrating a Polymer Web component"` phrase appears in this file only in the whole project, so looks like something's missing.
Might the actual asciidoc link be better?

---

*[documentation/web-components/creating-an-in-project-web-component.asciidoc, line 13 at r1](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/75#-LAHaIxm4PTXB8SNURqr:-LAHaIxm4PTXB8SNURqs:b-k3chge) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/9ec15567040c80400f68f70a25b29e1daf66062d/documentation/web-components/creating-an-in-project-web-component.asciidoc#L13)):*
> ```
> ##
> ```

This is Markdown syntax, which might be not supported everywhere: https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/#markdown-compatibility

> Markdown compatible syntax is only available when using Asciidoctor.

Whatever that means. Would it be better to be consistent and use `=` for headings, as everywhere else?
Lots of places affected, not only this one.

---

*[documentation/web-components/creating-an-in-project-web-component.asciidoc, line 44 at r1](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/75#-LAHVc603iZVaNtIH6RA:-LAHVc603iZVaNtIH6RB:b-6wntjx) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/9ec15567040c80400f68f70a25b29e1daf66062d/documentation/web-components/creating-an-in-project-web-component.asciidoc#L44)):*
> ```
> Creating a Java API
> ```

Missing also in the project.

---

*[documentation/web-components/creating-an-in-project-web-component.asciidoc, line 47 at r1](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/75#-LAH_STW4Ze0Njgg3cPh:-LAH_STW4Ze0Njgg3cPi:bh5yhf9) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/9ec15567040c80400f68f70a25b29e1daf66062d/documentation/web-components/creating-an-in-project-web-component.asciidoc#L47)):*
> ```
> ```java
> ```

Is there any reason you prefer this format over native asciidoc's 
```
[source,java]
----
```
one?

As mentioned above, markdown compatibility support is not guaranteed everywhere and we also use native one everywhere to validate the code snippets, can you use that one instead?
Lots of places affected, not only this one.

---

*[documentation/web-components/creating-an-in-project-web-component.asciidoc, line 56 at r1](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/75#-LAHV6H_-fPmDM1t9eVZ:-LAHV6H_-fPmDM1t9eV_:b4yyuef) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/9ec15567040c80400f68f70a25b29e1daf66062d/documentation/web-components/creating-an-in-project-web-component.asciidoc#L56)):*
> ```AsciiDoc
>     }
> }
> ```	
> ```

I propose to remove the tab symbol.

---

*[documentation/web-components/creating-another-type-of-addon.asciidoc, line 2 at r1](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/75#-LAHVugKAgMaadSMdPiW:-LAHVugKAgMaadSMdPiX:b-s03xrm) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/9ec15567040c80400f68f70a25b29e1daf66062d/documentation/web-components/creating-another-type-of-addon.asciidoc#L2)):*
> ```AsciiDoc
> ---
> title: Debugging a Web Component Integration
> ```

Title looks a bit different from the file contents and the file name, is it ok?

---

*[documentation/web-components/creating-another-type-of-addon.asciidoc, line 7 at r1](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/75#-LAHW0hV9u3TL-FDdmY4:-LAHW0hV9u3TL-FDdmY5:bm3eslz) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/9ec15567040c80400f68f70a25b29e1daf66062d/documentation/web-components/creating-another-type-of-addon.asciidoc#L7)):*
> ```
> dummy/../integrating-a-web-component
> ```


Does not look like a valid link, it's not even a correct asciidoc link syntax. 
This is not the only place, other *.ascciidoc files also contain dummy links, please fix them.

---

*[documentation/web-components/creating-java-api-for-a-web-component.asciidoc, line 24 at r1](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/75#-LAHfSGM8WxmVkwJg6lR:-LAHfSGM8WxmVkwJg6lS:b-yahsos) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/9ec15567040c80400f68f70a25b29e1daf66062d/documentation/web-components/creating-java-api-for-a-web-component.asciidoc#L24)):*
> ```
> the setter will return the property
> ```

getter

---

*[documentation/web-components/creating-java-api-for-a-web-component.asciidoc, line 160 at r1](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/75#-LAHgwz85OmauHLMnzqv:-LAHgwz85OmauHLMnzqw:b44ivtx) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/9ec15567040c80400f68f70a25b29e1daf66062d/documentation/web-components/creating-java-api-for-a-web-component.asciidoc#L160)):*
> ```
> example You
> ```

Guess the dot is missing.

---

*[documentation/web-components/creating-java-api-for-a-web-component.asciidoc, line 163 at r1](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/75#-LAHh6re8rWW8uwdC5cf:-LAHh6re8rWW8uwdC5cg:bphyfxa) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/9ec15567040c80400f68f70a25b29e1daf66062d/documentation/web-components/creating-java-api-for-a-web-component.asciidoc#L163)):*
> ```AsciiDoc
> 
> [TIP]
> As the event data expression is evaluated as JavaScript, you can control propagation behavior using e.g. `@EventData("event.preventDefault()") String ignored`. Don't do this. It ain't right. But as long as there is no other API to control this, you can do this.
> ```

I propose to remove this confusing tip since now we can do this after all.

---

*[documentation/web-components/creating-java-api-for-a-web-component.asciidoc, line 205 at r1](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/75#-LAHjfYI-SiAJ6MBRJ0a:-LAHjfYI-SiAJ6MBRJ0b:b-yve757) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/9ec15567040c80400f68f70a25b29e1daf66062d/documentation/web-components/creating-java-api-for-a-web-component.asciidoc#L205)):*
> ```AsciiDoc
> root.add(new Span("Hello"));
> root.add(new Span("World"));
> add(root);
> ```

Would it be nice to show the whole code after all changes for each example? 

---

*[documentation/web-components/creating-java-api-for-a-web-component.asciidoc, line 234 at r1](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/75#-LAHhho_0ttZIAQi32WO:-LAHhho_0ttZIAQi32WP:b-8f1mxe) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/9ec15567040c80400f68f70a25b29e1daf66062d/documentation/web-components/creating-java-api-for-a-web-component.asciidoc#L234)):*
> ```AsciiDoc
>         return icon;
>     }
> ```
> ```

`}` is missing. Also, corresponding java file contains 2 imports, here I see one only.
All this and many more mistakes would have been detected by our tests if you used correct ascciidoc code blocks and specified correct value in `@CodeFor` annotation in the corresponding java class.

---

*[documentation/web-components/creating-java-api-for-a-web-component.asciidoc, line 271 at r1](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/75#-LAHjV6bBu1PcUCCQ2zY:-LAHjV6bBu1PcUCCQ2zZ:b-5ns9pd) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/9ec15567040c80400f68f70a25b29e1daf66062d/documentation/web-components/creating-java-api-for-a-web-component.asciidoc#L271)):*
> ```AsciiDoc
> 
> [NOTE]
> You could extend `Button` directly instead of `Component` but then you would get all the public API of `Button` also
> ```

This example looks rather complicated, is this encapsulation usecase a frequent one? Would it be more beneficial to replace it with easier one?

---

*[documentation/web-components/integrating-a-web-component.asciidoc, line 7 at r1](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/75#-LAHixdt5hMXQrk93FRm:-LAHixdt5hMXQrk93FRn:bq0y7ik) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/9ec15567040c80400f68f70a25b29e1daf66062d/documentation/web-components/integrating-a-web-component.asciidoc#L7)):*
> ```AsciiDoc
> ---
> 
> Quick steps for the impatient. If everything does not work as smoothly as expected or you want to understand how things tie together, read on.
> ```

Are those two sentences really necessary? 
Would it be better to explain why do we need to do this at all, what is a web component, where to find them and why Flow needs those?

---

*[documentation/web-components/integrating-a-web-component.asciidoc, line 60 at r1](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/75#-LAHlUeQ3q--SDS3JEkq:-LAHlUeQ3q--SDS3JEkr:b-n0vdex) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/9ec15567040c80400f68f70a25b29e1daf66062d/documentation/web-components/integrating-a-web-component.asciidoc#L60)):*
> ```
> Use `dl.bintray.com` in your `pom.xml` to be able to use it immediately.
> ```

Example?

---

*[documentation/web-components/tutorial-flow-maven-plugin.asciidoc, line 0 at r1](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/75#-LAHj9rb8telySlhqYiK:-LAHj9rb8telySlhqYiL:b-1drd3e) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/9ec15567040c80400f68f70a25b29e1daf66062d/documentation/web-components/tutorial-flow-maven-plugin.asciidoc#L0)):*
This is currently the only place where flow-maven-plugin has its parameters described. Where should the user get the info about them now?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/75)*

**Comment by SomeoneToIgnore** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 19 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/75)*

**Comment by Artur-** [comment]
Review status: 21 of 36 files reviewed at latest revision, 19 unresolved discussions.

---

*[documentation/src/main/java/com/vaadin/flow/tutorial/webcomponent/ClickEvent.java, line 8 at r1](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/75#-LAHPfu64T2qJNVCobZH:-LAMSRP5EzThuPJ8FGQ2:b-896fix) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/9ec15567040c80400f68f70a25b29e1daf66062d/documentation/src/main/java/com/vaadin/flow/tutorial/webcomponent/ClickEvent.java#L8)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

Please do care, here and everywhere else.
This annotation is the way to check that the code in the tutorial and the file match. 
Without it we just check that some arbitrary file compiles which does not make much sense.
</blockquote></details>

Done.

---

*[documentation/src/main/java/com/vaadin/flow/tutorial/webcomponent/IconButton.java, line 29 at r1](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/75#-LAHPFRx0uXP-onpP-eT:-LAMSaGJ2PRr7CbD0Fch:b-896fix) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/9ec15567040c80400f68f70a25b29e1daf66062d/documentation/src/main/java/com/vaadin/flow/tutorial/webcomponent/IconButton.java#L29)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

Do users need this?
</blockquote></details>

Done.

---

*[documentation/web-components/creating-an-in-project-web-component.asciidoc, line 3 at r1](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/75#-LAHRmqU9JEEGVBmLBOe:-LAHzGsc7p9KHlkCW3LU:b-g0oeqo) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/9ec15567040c80400f68f70a25b29e1daf66062d/documentation/web-components/creating-an-in-project-web-component.asciidoc#L3)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

Previous tutorials have had sequential numbers, any reason to abandon this practice?
</blockquote></details>

The reason for not using sequential numbers would be do make it easy to insert pages. I can change it if it makes a difference

---

*[documentation/web-components/creating-an-in-project-web-component.asciidoc, line 7 at r1](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/75#-LAHS3ff6_uW-J_ZAP7x:-LAMWNBp6i8xWaZo17Nr:b-896fix) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/9ec15567040c80400f68f70a25b29e1daf66062d/documentation/web-components/creating-an-in-project-web-component.asciidoc#L7)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

> ```
> above
> ```

I don't see anything *above* related to the topic. Moreover, the `"Integrating a Polymer Web component"` phrase appears in this file only in the whole project, so looks like something's missing.
Might the actual asciidoc link be better?
</blockquote></details>

Done.

---

*[documentation/web-components/creating-an-in-project-web-component.asciidoc, line 13 at r1](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/75#-LAHaIxm4PTXB8SNURqr:-LAMWOCK4vhk2D4NOWvz:b-896fix) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/9ec15567040c80400f68f70a25b29e1daf66062d/documentation/web-components/creating-an-in-project-web-component.asciidoc#L13)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

> ```
> ##
> ```

This is Markdown syntax, which might be not supported everywhere: https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/#markdown-compatibility

> Markdown compatible syntax is only available when using Asciidoctor.

Whatever that means. Would it be better to be consistent and use `=` for headings, as everywhere else?
Lots of places affected, not only this one.
</blockquote></details>

Done.

---

*[documentation/web-components/creating-an-in-project-web-component.asciidoc, line 44 at r1](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/75#-LAHVc603iZVaNtIH6RA:-LAMWU6U2kdAStFe-gpy:b-896fix) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/9ec15567040c80400f68f70a25b29e1daf66062d/documentation/web-components/creating-an-in-project-web-component.asciidoc#L44)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

> ```
> Creating a Java API
> ```

Missing also in the project.
</blockquote></details>

Done.

---

*[documentation/web-components/creating-an-in-project-web-component.asciidoc, line 47 at r1](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/75#-LAH_STW4Ze0Njgg3cPh:-LAMWUe11_1rrpuH5yi2:b-896fix) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/9ec15567040c80400f68f70a25b29e1daf66062d/documentation/web-components/creating-an-in-project-web-component.asciidoc#L47)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

> ```
> ```java
> ```

Is there any reason you prefer this format over native asciidoc's 
```
[source,java]
----
```
one?

As mentioned above, markdown compatibility support is not guaranteed everywhere and we also use native one everywhere to validate the code snippets, can you use that one instead?
Lots of places affected, not only this one.
</blockquote></details>

Done.

---

*[documentation/web-components/creating-an-in-project-web-component.asciidoc, line 56 at r1](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/75#-LAHV6H_-fPmDM1t9eVZ:-LAMWeAN2IdjLHnrwNnL:b-896fix) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/9ec15567040c80400f68f70a25b29e1daf66062d/documentation/web-components/creating-an-in-project-web-component.asciidoc#L56)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

I propose to remove the tab symbol.
</blockquote></details>

Done.

---

*[documentation/web-components/creating-another-type-of-addon.asciidoc, line 2 at r1](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/75#-LAHVugKAgMaadSMdPiW:-LAMWf9V0wWwT3Q0Vs6z:b-896fix) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/9ec15567040c80400f68f70a25b29e1daf66062d/documentation/web-components/creating-another-type-of-addon.asciidoc#L2)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

Title looks a bit different from the file contents and the file name, is it ok?
</blockquote></details>

Done.

---

*[documentation/web-components/creating-another-type-of-addon.asciidoc, line 7 at r1](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/75#-LAHW0hV9u3TL-FDdmY4:-LAMWgXh2Gpb60_fDy2V:b-896fix) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/9ec15567040c80400f68f70a25b29e1daf66062d/documentation/web-components/creating-another-type-of-addon.asciidoc#L7)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

> ```
> dummy/../integrating-a-web-component
> ```


Does not look like a valid link, it's not even a correct asciidoc link syntax. 
This is not the only place, other *.ascciidoc files also contain dummy links, please fix them.
</blockquote></details>

Done.

---

*[documentation/web-components/creating-java-api-for-a-web-component.asciidoc, line 24 at r1](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/75#-LAHfSGM8WxmVkwJg6lR:-LAMWy7hDkhRYTHUAs8z:b-896fix) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/9ec15567040c80400f68f70a25b29e1daf66062d/documentation/web-components/creating-java-api-for-a-web-component.asciidoc#L24)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

> ```
> the setter will return the property
> ```

getter
</blockquote></details>

Done.

---

*[documentation/web-components/creating-java-api-for-a-web-component.asciidoc, line 160 at r1](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/75#-LAHgwz85OmauHLMnzqv:-LAMX-gm8XpbZ0Mi49_d:b-896fix) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/9ec15567040c80400f68f70a25b29e1daf66062d/documentation/web-components/creating-java-api-for-a-web-component.asciidoc#L160)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

> ```
> example You
> ```

Guess the dot is missing.
</blockquote></details>

Done.

---

*[documentation/web-components/creating-java-api-for-a-web-component.asciidoc, line 163 at r1](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/75#-LAHh6re8rWW8uwdC5cf:-LAMX7pxBviQJCje-okS:b-3756qk) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/9ec15567040c80400f68f70a25b29e1daf66062d/documentation/web-components/creating-java-api-for-a-web-component.asciidoc#L163)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

I propose to remove this confusing tip since now we can do this after all.
</blockquote></details>

Do you think it should say you can control propagation behavior or not mention it although it is often needed?

---

*[documentation/web-components/creating-java-api-for-a-web-component.asciidoc, line 205 at r1](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/75#-LAHjfYI-SiAJ6MBRJ0a:-LAMtCID9xCHC0luXYZG:b25v7n3) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/9ec15567040c80400f68f70a25b29e1daf66062d/documentation/web-components/creating-java-api-for-a-web-component.asciidoc#L205)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

Would it be nice to show the whole code after all changes for each example? 
</blockquote></details>

Added the full Slider code

---

*[documentation/web-components/creating-java-api-for-a-web-component.asciidoc, line 234 at r1](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/75#-LAHhho_0ttZIAQi32WO:-LAMXgTe895h6p3CZDOD:bc3qrln) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/9ec15567040c80400f68f70a25b29e1daf66062d/documentation/web-components/creating-java-api-for-a-web-component.asciidoc#L234)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

`}` is missing. Also, corresponding java file contains 2 imports, here I see one only.
All this and many more mistakes would have been detected by our tests if you used correct ascciidoc code blocks and specified correct value in `@CodeFor` annotation in the corresponding java class.
</blockquote></details>

Fixed. The code checker does not detect missing `}`. You only need one import if you use `icon.create()`, as it in turn imports `vaadin-icons.html`

---

*[documentation/web-components/creating-java-api-for-a-web-component.asciidoc, line 271 at r1](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/75#-LAHjV6bBu1PcUCCQ2zY:-LAMXP9MAbaDZsIV2Zjs:btt8av2) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/9ec15567040c80400f68f70a25b29e1daf66062d/documentation/web-components/creating-java-api-for-a-web-component.asciidoc#L271)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

This example looks rather complicated, is this encapsulation usecase a frequent one? Would it be more beneficial to replace it with easier one?
</blockquote></details>

I am sure it can be improved in another PR if somebody has a better example. Any ideas?

---

*[documentation/web-components/integrating-a-web-component.asciidoc, line 7 at r1](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/75#-LAHixdt5hMXQrk93FRm:-LAMYEL68rzKyK0VPSRe:b-dr6grr) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/9ec15567040c80400f68f70a25b29e1daf66062d/documentation/web-components/integrating-a-web-component.asciidoc#L7)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

Are those two sentences really necessary? 
Would it be better to explain why do we need to do this at all, what is a web component, where to find them and why Flow needs those?
</blockquote></details>

Simplified and added a webcomponennts info link

---

*[documentation/web-components/integrating-a-web-component.asciidoc, line 60 at r1](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/75#-LAHlUeQ3q--SDS3JEkq:-LAMZgEpAtQAI02ek5dW:b-896fix) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/9ec15567040c80400f68f70a25b29e1daf66062d/documentation/web-components/integrating-a-web-component.asciidoc#L60)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

> ```
> Use `dl.bintray.com` in your `pom.xml` to be able to use it immediately.
> ```

Example?
</blockquote></details>

Done.

---

*[documentation/web-components/tutorial-flow-maven-plugin.asciidoc, line  at r1](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/75#-LAHj9rb8telySlhqYiK:-LAIr4WN9i507urrBPzf:bc3iuud) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/9ec15567040c80400f68f70a25b29e1daf66062d/documentation/web-components/tutorial-flow-maven-plugin.asciidoc#L)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

This is currently the only place where flow-maven-plugin has its parameters described. Where should the user get the info about them now?
</blockquote></details>

Good question. 

What I as a user would have expected to find is a "Taking your app into production" as a top level topic which would focus on all kind of production mode issues/considerations. I would expect that to talk mostly on a generic level but mention how you create a production WAR using the Maven plugin and probably also using the Gradle plugin.

For the plugin documentation I think it would be the best approach to implement https://github.com/vaadin/flow/issues/3903, which means the docs should be in the plugin itself.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/75)*

**Comment by SomeoneToIgnore** [comment]
Compilation errors in the build.

---







*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow-and-components-documentation/75#-:-LAq9eS20O4HLILbd65L:bbh7jh3)*

**Comment by Artur-** [comment]
```
documentation/src/main/java/com/vaadin/flow/tutorial/webcomponent/DemoView.java:[55,31] incompatible types: cannot infer type-variable(s) T
    (argument mismatch; cannot infer functional interface descriptor for com.vaadin.flow.component.ComponentEventListener<com.vaadin.flow.component.ClickEvent>)
```
Seems like a compiler bug, works fine in Eclipse

---

Review status: 0 of 37 files reviewed at latest revision, 19 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow-and-components-documentation/75#-:-LAqFiEF3tMPX1yfboyD:b-9v2hr9)*

**Comment by pleku** [comment]
Reviewed 13 of 32 files at r1, 1 of 1 files at r2, 16 of 16 files at r3.
Review status: 29 of 37 files reviewed at latest revision, 19 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow-and-components-documentation/75)*

**Comment by pleku** [comment]
Reviewed 8 of 32 files at r1.
Review status: all files reviewed at latest revision, 19 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow-and-components-documentation/75)*

**Comment by pleku** [comment]
:lgtm:

@someonetoignore is still blocking with comments

---

Review status: all files reviewed at latest revision, 19 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow-and-components-documentation/75#-:-LArD6sj--DbLNQO05G1:bv1vo1t)*

**Pull request merged**
