### PR TITLE
Add a new tutorial about disabled components

### PR DESCRIPTION
**Pull request by denis-anisimov**
Fixes #3813

This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow-and-components-documentation/68)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---

*[a discussion](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/68#-L9P5X0M8qltNILcywvp:-L9P5X0M8qltNILcywvq:bpdimwi) (no related file):*
Work in progress. Blocked.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/68)*

**Comment by denis-anisimov** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/68#-L9P5X0M8qltNILcywvp:-L9Q0dXR9tti3e5Tor3l:b-5fni87) (no related file):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Work in progress. Blocked.
</blockquote></details>

Wait for the main functionality. The text itself is ready: needs to be merged with other related tutorials.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/68)*

**Comment by gilberto-torrezan** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[documentation/components/tutorial-disabled-components.asciidoc, line 1 at r2](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/68#-L9u4iuH9mYy3VYYx78o:-L9u4iuH9mYy3VYYx78p:bbdtaqy) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/b1800cb93a9c0acbc7371172630c32cbefbb8f93/documentation/components/tutorial-disabled-components.asciidoc#L1)):*
> ```AsciiDoc
> ---
> ```

You will need to merge this file with the https://github.com/vaadin/flow-and-components-documentation/blob/master/documentation/components/tutorial-enabled-state.asciidoc

Better review it after the merge, since some sections are talking about the same things.

---

*[documentation/src/main/html/DisabledComponents.html, line 16 at r2](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/68#-L9u4s7z9j2lpWU78Ev-:-L9u4s7z9j2lpWU78Ev0:b-byfdrb) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/b1800cb93a9c0acbc7371172630c32cbefbb8f93/documentation/src/main/html/DisabledComponents.html#L16)):*
> ```HTML
>          customElements.define(RegistrationForm.is, RegistrationForm);
>     </script>
> </dom-module>
> ```

New line

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/68)*

**Comment by denis-anisimov** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[documentation/src/main/html/DisabledComponents.html, line 16 at r2](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/68#-L9u4s7z9j2lpWU78Ev-:-LACj1sm2gPpEQo_iLpB:b-896fix) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/b1800cb93a9c0acbc7371172630c32cbefbb8f93/documentation/src/main/html/DisabledComponents.html#L16)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

New line
</blockquote></details>

Done.

---

*[documentation/components/tutorial-disabled-components.asciidoc, line 1 at r2](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/68#-L9u4iuH9mYy3VYYx78o:-LACdeRN4XQlBmn9wDgm:b-896fix) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/b1800cb93a9c0acbc7371172630c32cbefbb8f93/documentation/components/tutorial-disabled-components.asciidoc#L1)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

You will need to merge this file with the https://github.com/vaadin/flow-and-components-documentation/blob/master/documentation/components/tutorial-enabled-state.asciidoc

Better review it after the merge, since some sections are talking about the same things.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/68)*

**Comment by gilberto-torrezan** [comment]
Reviewed 5 of 5 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[documentation/components/tutorial-enabled-state.asciidoc, line 163 at r3](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/68#-LAD36JiAcfUQV1H9Oxk:-LAD36JiAcfUQV1H9Oxl:b-sn0rjl) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/48d779446e8b0b0a008643dac80767c6bc90160d/documentation/components/tutorial-enabled-state.asciidoc#L163)):*
> Similarly to the `synchronizeProperty` API method which allows to receive property updates
> for disabled components if it's called with `DisabledUpdateMode.ALWAYS` argument value you may
> use declarative way to do the same via `@Synchronize` annotation for the property getter
> in your component:

Missing a comma `,` between `argument value` and `you may`. Without it the paragraph is really confusing.

---

*[documentation/components/tutorial-enabled-state.asciidoc, line 181 at r3](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/68#-LAD47878wcjYp-jqzjw:-LAD4788EUh9tqLufpti:b-vlxe2z) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/48d779446e8b0b0a008643dac80767c6bc90160d/documentation/components/tutorial-enabled-state.asciidoc#L181)):*
> ```AsciiDoc
> To unblock DOM event for a disabled element using API method you may use 
> `addEventListener` overload which accepts extra parameter with value `DisabledUpdateMode.ALWAYS`.
> ```

It may seem obvious, bu it would be nice to have a code snippet showing the API, just like the previous section.

---

*[documentation/components/tutorial-enabled-state.asciidoc, line 185 at r3](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/68#-LAD3umZEKnue3zY0X9g:-LAD3umZEKnue3zY0X9h:b-ekbugp) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/48d779446e8b0b0a008643dac80767c6bc90160d/documentation/components/tutorial-enabled-state.asciidoc#L185)):*
> ```AsciiDoc
> use the extra parameter value `DisabledUpdateMode.ALWAYS` : 
> `@DomEvent(value="input", allowUpdates = DisabledUpdateMode.ALWAYS )`.
> ```

Same here about the code snippet.

---

*[documentation/components/tutorial-enabled-state.asciidoc, line 190 at r3](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/68#-LAD4IE96fKkBRd2I6aQ:-LAD4IE96fKkBRd2I6aR:b-qs5qbo) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/48d779446e8b0b0a008643dac80767c6bc90160d/documentation/components/tutorial-enabled-state.asciidoc#L190)):*
> ```AsciiDoc
> If you have server handler methods annotation with `@ClientDelegate` or 
> `@EventHandler` then you may unblock them for the disabled component specifying
>  `DisabledUpdateMode.ALWAYS` as a value: `@EventHandler(DisabledUpdateMode.ALWAYS)`. 
> ```

And here too.

---

*[documentation/src/main/html/DisabledComponents.html, line 16 at r2](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/68#-L9u4s7z9j2lpWU78Ev-:-LAD4PqH3zbcYW5K7KLe:b91skg3) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/b1800cb93a9c0acbc7371172630c32cbefbb8f93/documentation/src/main/html/DisabledComponents.html#L16)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not pushed.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/68)*

**Comment by gilberto-torrezan** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/68)*

**Comment by denis-anisimov** [comment]
Review status: 2 of 4 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[documentation/components/tutorial-enabled-state.asciidoc, line 163 at r3](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/68#-LAD36JiAcfUQV1H9Oxk:-LADErkNAdguzk6SjLSA:b-896fix) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/48d779446e8b0b0a008643dac80767c6bc90160d/documentation/components/tutorial-enabled-state.asciidoc#L163)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

> Similarly to the `synchronizeProperty` API method which allows to receive property updates
> for disabled components if it's called with `DisabledUpdateMode.ALWAYS` argument value you may
> use declarative way to do the same via `@Synchronize` annotation for the property getter
> in your component:

Missing a comma `,` between `argument value` and `you may`. Without it the paragraph is really confusing.
</blockquote></details>

Done.

---

*[documentation/components/tutorial-enabled-state.asciidoc, line 181 at r3](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/68#-LAD47878wcjYp-jqzjw:-LADH8-74bX0QjKUBEVM:b-896fix) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/48d779446e8b0b0a008643dac80767c6bc90160d/documentation/components/tutorial-enabled-state.asciidoc#L181)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

It may seem obvious, bu it would be nice to have a code snippet showing the API, just like the previous section.
</blockquote></details>

Done.

---

*[documentation/components/tutorial-enabled-state.asciidoc, line 185 at r3](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/68#-LAD3umZEKnue3zY0X9g:-LADH8Ir7-ArBt4x3Eud:b-896fix) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/48d779446e8b0b0a008643dac80767c6bc90160d/documentation/components/tutorial-enabled-state.asciidoc#L185)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

Same here about the code snippet.
</blockquote></details>

Done.

---

*[documentation/components/tutorial-enabled-state.asciidoc, line 190 at r3](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/68#-LAD4IE96fKkBRd2I6aQ:-LADH90A6P-YCcbutq_A:b-896fix) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/48d779446e8b0b0a008643dac80767c6bc90160d/documentation/components/tutorial-enabled-state.asciidoc#L190)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

And here too.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/68)*

**Comment by gilberto-torrezan** [comment]
Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[documentation/components/tutorial-enabled-state.asciidoc, line 218 at r5](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/68#-LADIA425sYLd86fsGNt:-LADIA438NpevhNEsTmX:b-31oe81) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/e0b4c3ba5d8dac3793ee1ecbe21714542ca89701/documentation/components/tutorial-enabled-state.asciidoc#L218)):*
> ```AsciiDoc
> }
> ----
>  
> ```

The dreaded new line.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/68)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[documentation/components/tutorial-enabled-state.asciidoc, line 218 at r5](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/68#-LADIA425sYLd86fsGNt:-LADJmRu5bPX1uPsftiM:b-896fix) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/e0b4c3ba5d8dac3793ee1ecbe21714542ca89701/documentation/components/tutorial-enabled-state.asciidoc#L218)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

The dreaded new line.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/68)*

**Comment by gilberto-torrezan** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[documentation/components/tutorial-enabled-state.asciidoc, line 218 at r5](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/68#-LADIA425sYLd86fsGNt:-LADKOEoEsQf0fuvd_I3:b-u3zqjc) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/e0b4c3ba5d8dac3793ee1ecbe21714542ca89701/documentation/components/tutorial-enabled-state.asciidoc#L218)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not pushed :-P

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/68)*

**Comment by gilberto-torrezan** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/68#-:-LADM5pHCKE2bPugbSUL:bnfp4nl)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[documentation/components/tutorial-enabled-state.asciidoc, line 218 at r5](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/68#-LADIA425sYLd86fsGNt:-LADM5TR3Q6ti4IOYIS2:b-tnmnv9) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/e0b4c3ba5d8dac3793ee1ecbe21714542ca89701/documentation/components/tutorial-enabled-state.asciidoc#L218)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

Not pushed :-P
</blockquote></details>

Shit.......
Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/68)*

**Comment by gilberto-torrezan** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/68#-:-LAH13cU5h8G5Gjsqnn3:bnfp4nl)*

**Pull request merged**
