### PR TITLE
Bogdan v10 platform rename

### PR DESCRIPTION
**Pull request by bogdanudrescu**
More changes renaming Vaadin 10 to Vaadin platform.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow-and-components-documentation/360)

### CODE REVIEW

**Comment by bogdanudrescu** [comment]
___
*[documentation/theme/using-component-themes.asciidoc, line 94 at r1](https://reviewable.io/reviews/vaadin/flow-and-components-documentation/360#-LTRcuk45NSfdj0ZnpiL:-LUjvXkw62GPiBsWedwF:b-896fix) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/cb1c8e7bee825db7d2a69d7d03230be967117cb8/documentation/theme/using-component-themes.asciidoc#L94)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Just remove this note
</blockquote></details>

Done.

**Comment by bogdanudrescu** [comment]
Please let me know about v10 in urls, it's not clear to me as I expressed it in some comments. And I actually suggest to take it as a separate issue since it's not something visible in the text for the user, maybe considering the original ticket.

**Comment by bogdanudrescu** [comment]
@denis-anisimov Originally I branched it from V10 and the discussion with @pleku was to change them there (quite some time ago, on V12 release day), then after put them in V12 branch.

**Comment by denis-anisimov** [comment]
> @denis-anisimov Originally I branched it from V10 and the discussion with @pleku was to change them there (quite some time ago, on V12 release day), then after put them in V12 branch.

Alright, I didn't notice the branch.

**Pull request merged**
