### PR TITLE
Update docs after making body full sized by default

### PR DESCRIPTION
**Pull request by pekam**
After https://github.com/vaadin/flow/pull/3821 `@BodySize(height = "100vh", width = "100vw")` is the default and the annotation is often not needed.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow-and-components-documentation/60)

### CODE REVIEW

**Comment by gilberto-torrezan** [comment]
Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[documentation/advanced/tutorial-bootstrap.asciidoc, line 176 at r1](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/60#-L9JY2Rr8KMNc7b7hdBM:-L9JY2Rr8KMNc7b7hdBN:b-t28k2e) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/9726768240ae61fb11e26154817ce860083def1b/documentation/advanced/tutorial-bootstrap.asciidoc#L176)):*
> ```AsciiDoc
> 
> [NOTE]
> It is recommended to use the default body size. If you don't apply any sizing to the `UI` / `body`,
> ```

This is slightly confusing. I suggest making it clear what means to use the default sizing (which is by not using any `@BodySize` at all) and what means to not apply any sizing (which is by using an empty `@BodySize` or a `@BodySize` with empty height/width).

Something like:

When using an empty `@BodySize` annotation (which doesn't apply any sizing for the `UI` / `body`), *you will not be able to use relative sizing* (% as unit) for any component,*unless the component has a parent that has defined size* using anything else than % as the unit. For that reason, it is recommended to use the default settings for the body size, by omitting the `@BodySize` annotation, or by declaring a specific size for it.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/60)*

**Comment by pekam** [comment]
Review status: 1 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[documentation/advanced/tutorial-bootstrap.asciidoc, line 176 at r1](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/60#-L9JY2Rr8KMNc7b7hdBM:-L9Jhh9f3u0qjqsX7_jt:b-896fix) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/9726768240ae61fb11e26154817ce860083def1b/documentation/advanced/tutorial-bootstrap.asciidoc#L176)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

This is slightly confusing. I suggest making it clear what means to use the default sizing (which is by not using any `@BodySize` at all) and what means to not apply any sizing (which is by using an empty `@BodySize` or a `@BodySize` with empty height/width).

Something like:

When using an empty `@BodySize` annotation (which doesn't apply any sizing for the `UI` / `body`), *you will not be able to use relative sizing* (% as unit) for any component,*unless the component has a parent that has defined size* using anything else than % as the unit. For that reason, it is recommended to use the default settings for the body size, by omitting the `@BodySize` annotation, or by declaring a specific size for it.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/60)*

**Comment by gilberto-torrezan** [comment]
Reviewed 8 of 8 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/60)*

**Comment by gilberto-torrezan** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/60#-:-L9Jk8ob653xged_jbuE:bnfp4nl)*

**Pull request merged**
