### PR TITLE
Update tutorial-routing-lifecycle.asciidoc

### PR DESCRIPTION
**Pull request by Legioth**
* Remove references to `BeforeNavigationEvent`
* Update descriptions of which observers are notified
* Add mention of programmatically registered listeners

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow-and-components-documentation/54)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[documentation/routing/tutorial-routing-lifecycle.asciidoc, line 78 at r1](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/54#-L8qbJWoDk2wgs8hylW_:-L8qbJWoDk2wgs8hylWa:b-871h47) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/2ee1c0e2b148e51a2f65e27e05eea089b99292db/documentation/routing/tutorial-routing-lifecycle.asciidoc#L78)):*
> ```
> The event will not be any further listeners or observers after `reroute`.
> ```

Something is missed here?

---

*[documentation/routing/tutorial-routing-lifecycle.asciidoc, line 118 at r1](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/54#-L8qc-Ft0fTTzIyjPZhv:-L8qc-Ft0fTTzIyjPZhw:b-gqswu0) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/2ee1c0e2b148e51a2f65e27e05eea089b99292db/documentation/routing/tutorial-routing-lifecycle.asciidoc#L118)):*
> ```
> At this point, is 
> ```

s/is/it/ ?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/54)*

**Comment by Legioth** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[documentation/routing/tutorial-routing-lifecycle.asciidoc, line 78 at r1](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/54#-L8qbJWoDk2wgs8hylW_:-L997ownA0LtCXOdqgFN:b-896fix) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/2ee1c0e2b148e51a2f65e27e05eea089b99292db/documentation/routing/tutorial-routing-lifecycle.asciidoc#L78)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> ```
> The event will not be any further listeners or observers after `reroute`.
> ```

Something is missed here?
</blockquote></details>

Done.

---

*[documentation/routing/tutorial-routing-lifecycle.asciidoc, line 118 at r1](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/54#-L8qc-Ft0fTTzIyjPZhv:-L997tY8DdPK711xZxt5:b-896fix) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/2ee1c0e2b148e51a2f65e27e05eea089b99292db/documentation/routing/tutorial-routing-lifecycle.asciidoc#L118)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> ```
> At this point, is 
> ```

s/is/it/ ?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/54)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[documentation/routing/tutorial-routing-lifecycle.asciidoc, line 78 at r1](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/54#-L8qbJWoDk2wgs8hylW_:-L9EGujC-pXG1LW_X10s:bx6k5tt) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/d62c2f29aafddebcdb75d4432e4af7f6c8517718/documentation/routing/tutorial-routing-lifecycle.asciidoc#L78)):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Don't see any changes.......

---

*[documentation/routing/tutorial-routing-lifecycle.asciidoc, line 118 at r1](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/54#-L8qc-Ft0fTTzIyjPZhv:-L9EH-dFDpmmk24ZtS-W:b59qznn) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/d62c2f29aafddebcdb75d4432e4af7f6c8517718/documentation/routing/tutorial-routing-lifecycle.asciidoc#L118)):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Forgot to commit ?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/54)*

**Comment by Legioth** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[documentation/routing/tutorial-routing-lifecycle.asciidoc, line 78 at r1](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/54#-L8qbJWoDk2wgs8hylW_:-L9EOwVODcF7Q8HL6V8T:b-896fix) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/d62c2f29aafddebcdb75d4432e4af7f6c8517718/documentation/routing/tutorial-routing-lifecycle.asciidoc#L78)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Don't see any changes.......
</blockquote></details>

Done.

---

*[documentation/routing/tutorial-routing-lifecycle.asciidoc, line 118 at r1](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/54#-L8qc-Ft0fTTzIyjPZhv:-L9EOwuW-GhMVBQ21_GQ:b-896fix) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/d62c2f29aafddebcdb75d4432e4af7f6c8517718/documentation/routing/tutorial-routing-lifecycle.asciidoc#L118)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Forgot to commit ?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/54)*

**Comment by denis-anisimov** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/54#-:-L9ERpuV0VEhjEFCDkjy:bnfp4nl)*

**Comment by Legioth** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[documentation/routing/tutorial-routing-lifecycle.asciidoc, line 65 at r2](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/54#-L9ExcJOE_oSEvd-FJQl:-L9F2VxUBqu23qK8IPNE:b-896fix) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/ec89316cceff4f5b3e8db0b637fd181b5d2e8c06/documentation/routing/tutorial-routing-lifecycle.asciidoc#L65)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

> ```
> The second fired event during naivation
> ```
The second event fired during navigation
</blockquote></details>

Done.

---

*[documentation/routing/tutorial-routing-lifecycle.asciidoc, line 114 at r2](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/54#-L9ExuhW6Mat5eMNvE4S:-L9F2WF8DfBFXh0nwWQa:b-896fix) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/ec89316cceff4f5b3e8db0b637fd181b5d2e8c06/documentation/routing/tutorial-routing-lifecycle.asciidoc#L114)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

> ```
> The third last last fired event during naivation
> ```
The third and last event fired during navigation
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/54)*

**Comment by caalador** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/54)*

**Pull request merged**
