### PR TITLE
Use correct spring package

### PR DESCRIPTION
**Pull request by ZheSun88**
Flow-spring-addon has been moved outside of flow. 
This should be picked up to V10 branch also

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow-and-components-documentation/205)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Reviewed 1 of 1 files at r1.
Review status: 1 unresolved discussion, 0 of 1 LGTMs obtained

---

*[documentation/pom.xml, line 53 at r1](https://reviewable.io/reviews/vaadin/flow-and-components-documentation/205#-LG4xbzI1GiXhdQUimfb:-LG4xbzI1GiXhdQUimfc:b82ns9k) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/810308a41347910190710a517fe91c774dec9dd4/documentation/pom.xml#L53)):*
> ```
> flow-spring-addon
> ```

So we still have this artifact with `1.0-SNAPSHOT`? (that's why it still works)

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow-and-components-documentation/205)*

**Comment by ZheSun88** [comment]
Review status: 1 unresolved discussion, 0 of 1 LGTMs obtained

---

*[documentation/pom.xml, line 53 at r1](https://reviewable.io/reviews/vaadin/flow-and-components-documentation/205#-LG4xbzI1GiXhdQUimfb:-LG4yGqm90tO6xsL_-15:bd28bb0) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/810308a41347910190710a517fe91c774dec9dd4/documentation/pom.xml#L53)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> ```
> flow-spring-addon
> ```

So we still have this artifact with `1.0-SNAPSHOT`? (that's why it still works)
</blockquote></details>

that have been left there since we move spring out of flow.. and yes, the snapshot is still there and last update was April. https://oss.sonatype.org/content/repositories/vaadin-snapshots/com/vaadin/flow-spring-addon/1.0-SNAPSHOT/

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow-and-components-documentation/205)*

**Comment by denis-anisimov** [comment]
:lgtm:

---

Review status: all discussions resolved, 0 of 1 LGTMs obtained, and 1 stale

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow-and-components-documentation/205#-:-LG4yvzlEdl8DomI12-J:bnfp4nl)*

**Comment by denis-anisimov** [comment]
Reviewed 1 of 1 files at r2.
Review status: all discussions resolved, 0 of 1 LGTMs obtained, and 1 stale

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow-and-components-documentation/205)*

**Comment by denis-anisimov** [comment]
:lgtm:

---

Review status: all discussions resolved, 0 of 1 LGTMs obtained, and 1 stale

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow-and-components-documentation/205#-:-LG4z9lmCJhGRez3tS-N:bnfp4nl)*

**Pull request merged**
