### PR TITLE
Clarify global styles and custom-style usage

### LINKED ISSUE #97: Improve “Including Style Sheets” docs
https://github.com/vaadin/flow-and-components-documentation/blob/master/documentation/importing-dependencies/tutorial-include-css.asciidoc

This document should include a warning about using a regular global stylesheet, as that can leak into components in polyfilled browsers.

For example, something like the following would most probably cause havoc in many components:

```css
div {
  margin: 20px;
}
```

In addition, we should document how to included CSS that is correctly scoped in all browsers – basically, to create a HTML import that contains an import for `custom-style.html` (from Polymer) and then a `<custom-style>` declaration including the CSS you want to add.

### PR DESCRIPTION
**Pull request by denis-anisimov**
Fixes #97

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow-and-components-documentation/154)

### CODE REVIEW

**Comment by caalador** [comment]
Found 3 problems with documentation
1. Tutorial importing-dependencies/tutorial-include-css.asciidoc L:86 contains the code line '---- ' that is not present in any of the corresponding code files
2. Tutorial importing-dependencies/tutorial-include-css.asciidoc L:88 contains the code line 'You may do this via `@HtmlImport` annotation if you put the content together in one file and import it:' that is not present in any of the corresponding code files
3. Tutorial importing-dependencies/tutorial-include-css.asciidoc L:90 contains the code line '[source,html]' that is not present in any of the corresponding code files

**Comment by gilberto-torrezan** [comment]
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[documentation/importing-dependencies/tutorial-include-css.asciidoc, line 65 at r1](https://reviewable.io/reviews/vaadin/flow-and-components-documentation/154#-LD_cvc_3sDPGRZgGFUt:-LD_cvc_3sDPGRZgGFUu:beg2wb1) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/d55378ee9c411b59d5be7ab2dcdedf26e1f52fb9/documentation/importing-dependencies/tutorial-include-css.asciidoc#L65)):*
> ```AsciiDoc
> doesn't have built-in web components support. A web component (see <<../web-components/integrating-a-web-component.asciidoc,Integrating a Web Component>>) normally uses its own styles defined for it and those styles are scoped to the web component.
> Global styles don't influence on the web component anyhow as well. 
> But this is true only if there is native web components browser support. 
> ```

Suggestion: add a link with which Browsers have full web component support. Could be the https://www.webcomponents.org/ landing page, for example.

---

*[documentation/importing-dependencies/tutorial-include-css.asciidoc, line 70 at r1](https://reviewable.io/reviews/vaadin/flow-and-components-documentation/154#-LD_dY-M15FSbtkk4xOm:-LD_dY-M15FSbtkk4xOn:b-rp7tgu) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/d55378ee9c411b59d5be7ab2dcdedf26e1f52fb9/documentation/importing-dependencies/tutorial-include-css.asciidoc#L70)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
> But if a user uses browser without this native support then the missing functionality
> is polyfilled and a web component in such browsers is not anymore a scoped unit
> but a regular part of the DOM tree and global styles work for it in the same
> way as for any other HTML element.
> ```
</details>


Missing some commas on here, and fixed small errors:

But if an user uses a browser without this native support, then the missing functionality
is polyfilled, and a web component in such browsers is not anymore a scoped unit
but a regular part of the DOM tree. In this case, global styles work for it in the same
way as for any other HTML element.

---

*[documentation/importing-dependencies/tutorial-include-css.asciidoc, line 110 at r1](https://reviewable.io/reviews/vaadin/flow-and-components-documentation/154#-LD_eFks5VAl5erLYuda:-LD_eFks5VAl5erLYudb:bmrs8kx) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/d55378ee9c411b59d5be7ab2dcdedf26e1f52fb9/documentation/importing-dependencies/tutorial-include-css.asciidoc#L110)):*
> ```AsciiDoc
> [TIP]
> 
> Similar topic is <<../theme/theming-crash-course#,Theming Crash Course>>
> ```

"Similar topic is... " ? I couldn't understand what does this mean. Would it be something like "To learn more, see theming" or "This is also relevant for theming" ?

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow-and-components-documentation/154)*

**Comment by denis-anisimov** [comment]
It has been caused by one extra space after closing `---`, thanks.

---

Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[documentation/importing-dependencies/tutorial-include-css.asciidoc, line 65 at r1](https://reviewable.io/reviews/vaadin/flow-and-components-documentation/154#-LD_cvc_3sDPGRZgGFUt:-LD_i6NJ3H_Cz-S4bYqs:b-896fix) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/d55378ee9c411b59d5be7ab2dcdedf26e1f52fb9/documentation/importing-dependencies/tutorial-include-css.asciidoc#L65)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

Suggestion: add a link with which Browsers have full web component support. Could be the https://www.webcomponents.org/ landing page, for example.
</blockquote></details>

Done.

---

*[documentation/importing-dependencies/tutorial-include-css.asciidoc, line 70 at r1](https://reviewable.io/reviews/vaadin/flow-and-components-documentation/154#-LD_dY-M15FSbtkk4xOm:-LD_iN8dBDds4pdQqZ_5:b-896fix) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/d55378ee9c411b59d5be7ab2dcdedf26e1f52fb9/documentation/importing-dependencies/tutorial-include-css.asciidoc#L70)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

> ```
> But if a user uses browser without this native support then the missing functionality
> is polyfilled and a web component in such browsers is not anymore a scoped unit
> but a regular part of the DOM tree and global styles work for it in the same
> way as for any other HTML element.
> ```

Missing some commas on here, and fixed small errors:

But if an user uses a browser without this native support, then the missing functionality
is polyfilled, and a web component in such browsers is not anymore a scoped unit
but a regular part of the DOM tree. In this case, global styles work for it in the same
way as for any other HTML element.
</blockquote></details>

Done.

---

*[documentation/importing-dependencies/tutorial-include-css.asciidoc, line 110 at r1](https://reviewable.io/reviews/vaadin/flow-and-components-documentation/154#-LD_eFks5VAl5erLYuda:-LD_iYp22cbT2p_V3sai:bzbdsft) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/d55378ee9c411b59d5be7ab2dcdedf26e1f52fb9/documentation/importing-dependencies/tutorial-include-css.asciidoc#L110)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

"Similar topic is... " ? I couldn't understand what does this mean. Would it be something like "To learn more, see theming" or "This is also relevant for theming" ?
</blockquote></details>

Done.

The section mentioned here also contains info about `custom-style` (even though it's not clear from the title). The content of the section also describes `custom-style` with a context of theming. That's why I mentioned it here.
Not sure that this is "to learn more" but let it be so.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow-and-components-documentation/154#-:-LD_gbN858te-lZhD64c:bjqtafn)*

**Comment by gilberto-torrezan** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow-and-components-documentation/154#-:-LD_kL9T0YmTe_pgs5uS:bnfp4nl)*

**Pull request merged**
