### PR TITLE
Update loading indicator documentation

### PR DESCRIPTION
**Pull request by pleku**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow-and-components-documentation/188)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Reviewed 15 of 15 files at r1.
Review status: 1 unresolved discussion, 0 of 1 LGTMs obtained

---

*[documentation/advanced/tutorial-loading-indicator.asciidoc, line 79 at r1](https://reviewable.io/reviews/vaadin/flow-and-components-documentation/188#-LF1E4GbEK-ul0jJgrza:-LF1E4GbEK-ul0jJgrzb:bxfvtf7) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/ea4c2bc96f0c809d1f8a121f44961dbaa4a4df01/documentation/advanced/tutorial-loading-indicator.asciidoc#L79)):*
> ```
> shows how to show
> ```

`shows how to show` is a bit confusing. Would be better to replace one word with similar meaning.
E.g. `shows how to style` or whatever.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow-and-components-documentation/188)*

**Comment by caalador** [comment]
Build fails on an compilation error.
```
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /opt/agent/work/ea5f52ef8a8692b5/documentation/src/main/java/com/vaadin/flow/tutorial/advanced/MainLayout.java:[20,13] cannot find symbol
   symbol:   method setAppyDefaultTheme(boolean)
   location: variable conf of type com.vaadin.flow.component.page.LoadingIndicatorConfiguration
[INFO] 1 error
```

**Comment by pleku** [comment]
Review status: 1 unresolved discussion, 0 of 1 LGTMs obtained

---

*[documentation/advanced/tutorial-loading-indicator.asciidoc, line 79 at r1](https://reviewable.io/reviews/vaadin/flow-and-components-documentation/188#-LF1E4GbEK-ul0jJgrza:-LFveUx55gSw6PyhzIdX:b-896fix) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/1e9c8573e5b89e8e75abd1b0c2b9dd40f2b36880/documentation/advanced/tutorial-loading-indicator.asciidoc#L79)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> ```
> shows how to show
> ```

`shows how to show` is a bit confusing. Would be better to replace one word with similar meaning.
E.g. `shows how to style` or whatever.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow-and-components-documentation/188)*

**Comment by denis-anisimov** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all discussions resolved, 0 of 1 LGTMs obtained, and 1 stale

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow-and-components-documentation/188#-:-LFvgGNQEEdecFhyARJ3:bnfp4nl)*

**Pull request merged**
