### PR TITLE
Update documentation related to the behavior of the Lumo theme, which is now used by default

### PR DESCRIPTION
**Pull request by gilberto-torrezan**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow-and-components-documentation/59)

### CODE REVIEW

**Comment by pekam** [comment]
Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---

*[a discussion](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/59#-L9H2vN9EFBFLn5kUmoq:-L9H2vN9EFBFLn5kUmor:bslgabb) (no related file):*
There are still examples in the documentation, which are not related to theming, but where the `@Theme(Lumo.class)` is used by default, like this: https://github.com/vaadin/flow-and-components-documentation/blob/master/documentation/advanced/tutorial-push-broadcaster.asciidoc

You can find all of them with search:
https://github.com/vaadin/flow-and-components-documentation/search?utf8=%E2%9C%93&q=Theme%28Lumo&type=

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/59)*

**Comment by gilberto-torrezan** [comment]
Review status: 0 of 12 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/59#-L9H2vN9EFBFLn5kUmoq:-L9JU2MPCV6CXOFVUvVj:b7xzt1m) (no related file):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

There are still examples in the documentation, which are not related to theming, but where the `@Theme(Lumo.class)` is used by default, like this: https://github.com/vaadin/flow-and-components-documentation/blob/master/documentation/advanced/tutorial-push-broadcaster.asciidoc

You can find all of them with search:
https://github.com/vaadin/flow-and-components-documentation/search?utf8=%E2%9C%93&q=Theme%28Lumo&type=
</blockquote></details>

Updated remaining documents.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/59)*

**Comment by ZheSun88** [comment]
Reviewed 4 of 4 files at r1, 8 of 8 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/59)*

**Comment by ZheSun88** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/59#-:-L9Je-iK9YNoPT8aVWqW:bnfp4nl)*

**Pull request merged**
