### PR TITLE
Update web components tutorial

### PR DESCRIPTION
**Pull request by denis-anisimov**
Make webjars as a recommended way to use webcomponents.
Make bower based tutorial deprecated.
Make maven plugin as a recommended way to set up project for production.
Make old transpilation tutorial optional.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow-and-components-documentation/9)

### CODE REVIEW

**Comment by caalador** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[web-components/tutorial-webcomponent-basic.asciidoc, line 38 at r1](https://reviewable.io:443/reviews/vaadin/flow-and-components-documentation/9#-L4tRR0nVhfytmWBG7Tv:-L4tRR0nVhfytmWBG7Tw:b-hyfgom) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/782a7680a948274a90d244050ca01a32ef3676c6/web-components/tutorial-webcomponent-basic.asciidoc#L38)):*
> contains a client side code
should be just `contains client side code`

---

*[web-components/tutorial-webcomponent-basic.asciidoc, line 39 at r1](https://reviewable.io:443/reviews/vaadin/flow-and-components-documentation/9#-L4tRe9xxfv1ibrOdVWA:-L4tRe9xxfv1ibrOdVWB:b-c7s0h6) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/782a7680a948274a90d244050ca01a32ef3676c6/web-components/tutorial-webcomponent-basic.asciidoc#L39)):*
> ```AsciiDoc
> 
> The imported file `paper-slider.html` contains a client side code which needs to be available as a web resource. 
> The best way to do it is to use webjars. In order to add a webjar into the project, 
> ```

Is it the best way or should it be the recommended way?

---

*[web-components/tutorial-webcomponent-basic.asciidoc, line 40 at r1](https://reviewable.io:443/reviews/vaadin/flow-and-components-documentation/9#-L4tRoWCPx22lFfo0yHr:-L4tRoWCPx22lFfo0yHs:b-q5sj2g) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/782a7680a948274a90d244050ca01a32ef3676c6/web-components/tutorial-webcomponent-basic.asciidoc#L40)):*
> In order to add a webjar into the project,
> you have to simply specify a project dependency.
I'd suggest
`To add a webjar to the project you only need to specify it as a project dependency.`

---

*[web-components/tutorial-webcomponents-es5.asciidoc, line 457 at r1](https://reviewable.io:443/reviews/vaadin/flow-and-components-documentation/9#-L4tT4ZQLDMOB4aTaAs2:-L4tT4ZQLDMOB4aTaAs3:b-3jv99e) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/782a7680a948274a90d244050ca01a32ef3676c6/web-components/tutorial-webcomponents-es5.asciidoc#L457)):*
> ```AsciiDoc
> ----
> @Tag("my-component")
> @HtmlImport("frontend/components/my-component.html")
> ```

Won't this now resolve to `frontend/frontend/components...`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow-and-components-documentation/9)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[web-components/tutorial-webcomponent-basic.asciidoc, line 38 at r1](https://reviewable.io:443/reviews/vaadin/flow-and-components-documentation/9#-L4tRR0nVhfytmWBG7Tv:-L4tY7eSu_rqCiiIpToa:b-896fix) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/782a7680a948274a90d244050ca01a32ef3676c6/web-components/tutorial-webcomponent-basic.asciidoc#L38)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

> contains a client side code
should be just `contains client side code`
</blockquote></details>

Done.

---

*[web-components/tutorial-webcomponent-basic.asciidoc, line 39 at r1](https://reviewable.io:443/reviews/vaadin/flow-and-components-documentation/9#-L4tRe9xxfv1ibrOdVWA:-L4tYC5s8FEYaq7JOZEB:b-896fix) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/782a7680a948274a90d244050ca01a32ef3676c6/web-components/tutorial-webcomponent-basic.asciidoc#L39)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

Is it the best way or should it be the recommended way?
</blockquote></details>

Done.

---

*[web-components/tutorial-webcomponent-basic.asciidoc, line 40 at r1](https://reviewable.io:443/reviews/vaadin/flow-and-components-documentation/9#-L4tRoWCPx22lFfo0yHr:-L4tYHLr9cvhFsaXcxtG:b-896fix) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/782a7680a948274a90d244050ca01a32ef3676c6/web-components/tutorial-webcomponent-basic.asciidoc#L40)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

> In order to add a webjar into the project,
> you have to simply specify a project dependency.
I'd suggest
`To add a webjar to the project you only need to specify it as a project dependency.`

</blockquote></details>

Done.

---

*[web-components/tutorial-webcomponents-es5.asciidoc, line 457 at r1](https://reviewable.io:443/reviews/vaadin/flow-and-components-documentation/9#-L4tT4ZQLDMOB4aTaAs2:-L4tYJnF9XVOQaN44ofS:b-eh1viw) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/782a7680a948274a90d244050ca01a32ef3676c6/web-components/tutorial-webcomponents-es5.asciidoc#L457)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

Won't this now resolve to `frontend/frontend/components...`?
</blockquote></details>

Should not............
The URL has no any protocol, so technically it should be resolved to context  (well, there is no `context` protocol but in most cases it's the same)
So the URL technically is `context://frontend/components/my-component.html`.
Which is the same as `frontend://components/my-component.html`.

OR is the default protocol is `frontend` now ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow-and-components-documentation/9)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[web-components/tutorial-webcomponents-es5.asciidoc, line 457 at r1](https://reviewable.io:443/reviews/vaadin/flow-and-components-documentation/9#-L4tT4ZQLDMOB4aTaAs2:-L4tZ0uZHVFBj4URDFYS:b-d1sy9b) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/782a7680a948274a90d244050ca01a32ef3676c6/web-components/tutorial-webcomponents-es5.asciidoc#L457)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Should not............
The URL has no any protocol, so technically it should be resolved to context  (well, there is no `context` protocol but in most cases it's the same)
So the URL technically is `context://frontend/components/my-component.html`.
Which is the same as `frontend://components/my-component.html`.

OR is the default protocol is `frontend` now ?
</blockquote></details>

Oh crap.
You are right.
I forgot about this.
Now `frontend` is the default protocol.
Thanks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow-and-components-documentation/9)*

**Comment by caalador** [comment]
Push changes?

---

Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow-and-components-documentation/9#-:-L4uG-YvefHlNFsNV89R:b-otvw0z)*

**Comment by denis-anisimov** [comment]
yeah........
Mixing up repositories.

---

Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow-and-components-documentation/9#-:-L4uHe2o-OmG6jWq-oee:b4uuu5l)*

**Comment by caalador** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow-and-components-documentation/9#-:-L4uOuQljWf4gsdTlMlb:bnfp4nl)*

**Comment by ZheSun88** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[web-components/tutorial-how-to-use-webjars.asciidoc, line 23 at r2](https://reviewable.io:443/reviews/vaadin/flow-and-components-documentation/9#-L4uO6DVD5SMt2gQ74P8:-L4uO6DVD5SMt2gQ74P9:bzcnpcq) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/dc9a8f4694fbfed408bb38e1388f508c29316192/web-components/tutorial-how-to-use-webjars.asciidoc#L23)):*
> ```AsciiDoc
> ----
> <dependency>
>     <groupId>org.webjars.bower</groupId>
> ```

as we are using the new webjars style.  maybe we should update this also. 

<dependency>
    <groupId>org.webjars.bowergithub.polymerelements</groupId>
    <artifactId>paper-button</artifactId>
    <version>2.0.0</version>
</dependency>

---

*[web-components/tutorial-how-to-use-webjars.asciidoc, line 49 at r2](https://reviewable.io:443/reviews/vaadin/flow-and-components-documentation/9#-L4uPm8kZXUfo-0ZS7dy:-L4uPm8kZXUfo-0ZS7dz:bgnoflo) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/dc9a8f4694fbfed408bb38e1388f508c29316192/web-components/tutorial-how-to-use-webjars.asciidoc#L49)):*
> ```AsciiDoc
> ----
> <dependency>
>     <groupId>org.webjars.bower</groupId>
> ```

Here also.

---

*[web-components/tutorial-how-to-use-webjars.asciidoc, line 91 at r2](https://reviewable.io:443/reviews/vaadin/flow-and-components-documentation/9#-L4uPy5IFVIM8u8pVYoL:-L4uPy5IFVIM8u8pVYoM:b-uqb3dv) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/dc9a8f4694fbfed408bb38e1388f508c29316192/web-components/tutorial-how-to-use-webjars.asciidoc#L91)):*
> ```AsciiDoc
> 
> === WebJar is not in BinTray
> ```

This way of deploying the new webjars is not correct at the moment, because there might be no public API for the new webjars.. @someonetoignore is it? 

---

*[web-components/tutorial-webcomponent-basic.asciidoc, line 45 at r2](https://reviewable.io:443/reviews/vaadin/flow-and-components-documentation/9#-L4uQFQwwwvYpIjdC1Kr:-L4uQFQwwwvYpIjdC1Ks:b-qep4ty) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/dc9a8f4694fbfed408bb38e1388f508c29316192/web-components/tutorial-webcomponent-basic.asciidoc#L45)):*
> ```AsciiDoc
> ----
> <dependency>
>     <groupId>org.webjars.bower</groupId>
> ```

this example needs to update. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow-and-components-documentation/9)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[web-components/tutorial-how-to-use-webjars.asciidoc, line 23 at r2](https://reviewable.io:443/reviews/vaadin/flow-and-components-documentation/9#-L4uO6DVD5SMt2gQ74P8:-L4uV4u1ejDAcRQ0GWeW:b-jhpbfk) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/dc9a8f4694fbfed408bb38e1388f508c29316192/web-components/tutorial-how-to-use-webjars.asciidoc#L23)):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

as we are using the new webjars style.  maybe we should update this also. 

<dependency>
    <groupId>org.webjars.bowergithub.polymerelements</groupId>
    <artifactId>paper-button</artifactId>
    <version>2.0.0</version>
</dependency>
</blockquote></details>

I don't understand the markup in your comment.
Most likely markup is removed .
Please reread your comment and make it so that I can read it properly.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow-and-components-documentation/9)*

**Comment by ZheSun88** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[web-components/tutorial-how-to-use-webjars.asciidoc, line 23 at r2](https://reviewable.io:443/reviews/vaadin/flow-and-components-documentation/9#-L4uO6DVD5SMt2gQ74P8:-L4uVcZx6tNw3dXZORG_:b-fdscca) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/dc9a8f4694fbfed408bb38e1388f508c29316192/web-components/tutorial-how-to-use-webjars.asciidoc#L23)):*
> <dependency>
>     <groupId>org.webjars.bowergithub.polymerelements</groupId>
>     <artifactId>paper-button</artifactId>
>     <version>2.0.0</version>
> </dependency>

will it work in this way?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow-and-components-documentation/9)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[web-components/tutorial-how-to-use-webjars.asciidoc, line 23 at r2](https://reviewable.io:443/reviews/vaadin/flow-and-components-documentation/9#-L4uO6DVD5SMt2gQ74P8:-L4uVzCW96MMtE9K9hwd:b2nhky0) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/dc9a8f4694fbfed408bb38e1388f508c29316192/web-components/tutorial-how-to-use-webjars.asciidoc#L23)):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

> <dependency>
>     <groupId>org.webjars.bowergithub.polymerelements</groupId>
>     <artifactId>paper-button</artifactId>
>     <version>2.0.0</version>
> </dependency>

will it work in this way?
</blockquote></details>

No.

---

*[web-components/tutorial-how-to-use-webjars.asciidoc, line 91 at r2](https://reviewable.io:443/reviews/vaadin/flow-and-components-documentation/9#-L4uPy5IFVIM8u8pVYoL:-L4uVc2yLcuKJQ7L74pZ:b6z6uob) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/dc9a8f4694fbfed408bb38e1388f508c29316192/web-components/tutorial-how-to-use-webjars.asciidoc#L91)):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

This way of deploying the new webjars is not correct at the moment, because there might be no public API for the new webjars.. @someonetoignore is it? 
</blockquote></details>

May be.
But I don't see how this relates to the PR.
Let's not fix everything here.
Please create a ticket for this.

Out of the scope of the PR and the ticket which it fixes.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow-and-components-documentation/9)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[web-components/tutorial-how-to-use-webjars.asciidoc, line 23 at r2](https://reviewable.io:443/reviews/vaadin/flow-and-components-documentation/9#-L4uO6DVD5SMt2gQ74P8:-L4uW45RIkfgRbRokMaz:b-9s87jw) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/dc9a8f4694fbfed408bb38e1388f508c29316192/web-components/tutorial-how-to-use-webjars.asciidoc#L23)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

No.
</blockquote></details>

What is the group id in this string,
what's the artifact ?
`2.0.0`  I guess it's the version

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow-and-components-documentation/9)*

**Comment by ZheSun88** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[web-components/tutorial-how-to-use-webjars.asciidoc, line 23 at r2](https://reviewable.io:443/reviews/vaadin/flow-and-components-documentation/9#-L4uO6DVD5SMt2gQ74P8:-L4uW4NjQYh0vcubmJ0B:b-2kno0n) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/dc9a8f4694fbfed408bb38e1388f508c29316192/web-components/tutorial-how-to-use-webjars.asciidoc#L23)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

What is the group id in this string,
what's the artifact ?
`2.0.0`  I guess it's the version
</blockquote></details>

```
 <dependency>
     <groupId>org.webjars.bowergithub.polymerelements</groupId>
     <artifactId>paper-button</artifactId>
     <version>2.0.0</version>
 </dependency>
```
here you are... sorry for that

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow-and-components-documentation/9)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[web-components/tutorial-how-to-use-webjars.asciidoc, line 23 at r2](https://reviewable.io:443/reviews/vaadin/flow-and-components-documentation/9#-L4uO6DVD5SMt2gQ74P8:-L4uWRZTdJHl6uXqkKdG:b-bqm4z5) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/dc9a8f4694fbfed408bb38e1388f508c29316192/web-components/tutorial-how-to-use-webjars.asciidoc#L23)):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

```
 <dependency>
     <groupId>org.webjars.bowergithub.polymerelements</groupId>
     <artifactId>paper-button</artifactId>
     <version>2.0.0</version>
 </dependency>
```
here you are... sorry for that
</blockquote></details>

Does it work at all?
How may I check that this group id and artifact id is available as a web jar ?
`webjars.org` doesn't show such webjar.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow-and-components-documentation/9)*

**Comment by ZheSun88** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[web-components/tutorial-how-to-use-webjars.asciidoc, line 23 at r2](https://reviewable.io:443/reviews/vaadin/flow-and-components-documentation/9#-L4uO6DVD5SMt2gQ74P8:-L4uWrGr4rpo_BApGMB7:b-tm4ipt) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/dc9a8f4694fbfed408bb38e1388f508c29316192/web-components/tutorial-how-to-use-webjars.asciidoc#L23)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Does it work at all?
How may I check that this group id and artifact id is available as a web jar ?
`webjars.org` doesn't show such webjar.
</blockquote></details>

that is the new webjars we are using in flow. and you can see from here. https://github.com/vaadin/flow/blob/master/webjars-bom/pom.xml. 

and this new webjars are not deployed via `webjars.org` at this moment.  but you can check the `bintray`(https://dl.bintray.com/webjars/maven/org/webjars/).. the new format are there. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow-and-components-documentation/9)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[web-components/tutorial-how-to-use-webjars.asciidoc, line 23 at r2](https://reviewable.io:443/reviews/vaadin/flow-and-components-documentation/9#-L4uO6DVD5SMt2gQ74P8:-L4uY6B6ITe0YJ0f99s2:b8jrqks) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/dc9a8f4694fbfed408bb38e1388f508c29316192/web-components/tutorial-how-to-use-webjars.asciidoc#L23)):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

that is the new webjars we are using in flow. and you can see from here. https://github.com/vaadin/flow/blob/master/webjars-bom/pom.xml. 

and this new webjars are not deployed via `webjars.org` at this moment.  but you can check the `bintray`(https://dl.bintray.com/webjars/maven/org/webjars/).. the new format are there. 
</blockquote></details>

Let's say: no.

I may change it here but I'm not going to change all related to this things 
because it looks like the tutorial has to be rewritten.
Those changes have no any relation to the PR and the ticket which it fixes.
Please create a ticket about this.

I didn't change this part. So it's out of the scope of this PR.
Won't be fixed here.

---

*[web-components/tutorial-how-to-use-webjars.asciidoc, line 49 at r2](https://reviewable.io:443/reviews/vaadin/flow-and-components-documentation/9#-L4uPm8kZXUfo-0ZS7dy:-L4uY_97p6en0FXBHGHK:bmc45ef) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/dc9a8f4694fbfed408bb38e1388f508c29316192/web-components/tutorial-how-to-use-webjars.asciidoc#L49)):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

Here also.
</blockquote></details>

Won't be fixed here.

---

*[web-components/tutorial-webcomponent-basic.asciidoc, line 45 at r2](https://reviewable.io:443/reviews/vaadin/flow-and-components-documentation/9#-L4uQFQwwwvYpIjdC1Kr:-L4uYarp_TKIgQfP7Ub8:b-fv18h1) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/dc9a8f4694fbfed408bb38e1388f508c29316192/web-components/tutorial-webcomponent-basic.asciidoc#L45)):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

this example needs to update. 
</blockquote></details>

Wont be fixed here event though it's changed.
There should be a separate PR which fixes all those things at once.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow-and-components-documentation/9)*

**Comment by ZheSun88** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[web-components/tutorial-how-to-use-webjars.asciidoc, line 23 at r2](https://reviewable.io:443/reviews/vaadin/flow-and-components-documentation/9#-L4uO6DVD5SMt2gQ74P8:-L4uZ2Dg2s3jBQ2_pYOP:b-9alsc6) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/dc9a8f4694fbfed408bb38e1388f508c29316192/web-components/tutorial-how-to-use-webjars.asciidoc#L23)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Let's say: no.

I may change it here but I'm not going to change all related to this things 
because it looks like the tutorial has to be rewritten.
Those changes have no any relation to the PR and the ticket which it fixes.
Please create a ticket about this.

I didn't change this part. So it's out of the scope of this PR.
Won't be fixed here.
</blockquote></details>

okay, that is fine. Could you create a ticket for that? i will resolve this and other comments

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow-and-components-documentation/9)*

**Comment by denis-anisimov** [comment]
Review status: 6 of 7 files reviewed at latest revision, all discussions resolved.

---

*[web-components/tutorial-how-to-use-webjars.asciidoc, line 23 at r2](https://reviewable.io:443/reviews/vaadin/flow-and-components-documentation/9#-L4uO6DVD5SMt2gQ74P8:-L4uZ_CekDoSBVw4_8f6:bbqo3hd) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/dc9a8f4694fbfed408bb38e1388f508c29316192/web-components/tutorial-how-to-use-webjars.asciidoc#L23)):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

okay, that is fine. Could you create a ticket for that? i will resolve this and other comments
</blockquote></details>

No , I can't create a ticket because I don't complain about those things.
And the reason : I don't know anything about this.

This is you who complains about this. You know details.
I don't see any reason to create a ticket by the person who has 0 knowledge of the issue.
For me the current code is totally fine. I don't see an issue.
I'm OK with the fact that there is an issue. But I don't know the details.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow-and-components-documentation/9)*

**Comment by denis-anisimov** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow-and-components-documentation/9)*

**Pull request merged**
