### PR TITLE
Update tutorial-template-basic.asciidoc

### PR DESCRIPTION
**Pull request by atistrcsn**
If the template path has a starting forward slash ('/")like an absolute path, then an exception is thrown: 
"Can't find resource '/src/***/***.html' via the servlet context ".

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow-and-components-documentation/460)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
In fact the exception will be thrown even with this change: it's just a question of the resource location.
The URI used in the `HtmlImport` should be properly located and the exact location is not mentioned in this tutorial.
But leading slash is rather a mistake in the real examples. So let's go with this PR.

**Comment by atistrcsn** [comment]
Sure, thanks for review it.
I will update, but unfortunately only next week. Right now I am in the
middle of rolling out a big production code... of course with Vaadin ;-)

Wish me luck!

Cheers!

Sun Zhe <notifications@github.com> ezt írta (időpont: 2019. febr. 22., P
8:40):

**Comment by atistrcsn** [comment]
Hi @ZheSun88 . I patched the source code too but I am not sure about my workflow here on GitHub. Never contributed really before :) So I made the changes in a branch named "patch-2", merged it to "patch-1" (this PR) and pushed the button with the caption "Update branch". I am waiting now. Can you affirm that it's O.K. this way? Thanks.

**Comment by ZheSun88** [comment]
Hey @atistrcsn , you made it.  now everything looks okay. Thanks for your contribution again.

**Pull request merged**
