### PR TITLE
Extend doc for @Id semantic.

### LINKED ISSUE #41: Clarify @Id documentation
Update https://github.com/vaadin/flow-and-components-documentation/blob/master/polymer-templates/tutorial-template-components.asciidoc to clarify that properties and children defined in the template won't be available through the server-side API.

Also describe the implications of this that would not be mitigated by https://github.com/vaadin/flow/issues/3713, i.e. that `getChildren()` or `getText()` will be empty and that property values defined through the template won't be available.

### PR DESCRIPTION
**Pull request by denis-anisimov**
Fixes #41

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow-and-components-documentation/44)

### CODE REVIEW

**Comment by caalador** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[documentation/polymer-templates/tutorial-template-components.asciidoc, line 80 at r1](https://reviewable.io:443/reviews/vaadin/flow-and-components-documentation/44#-L8VqbeyVsp3hNwaWJmy:-L8VqbeyVsp3hNwaWJmz:bip2lg1) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/c7ec8a2ec1af3e1cbc51187acce1cc2cb23b28cc/documentation/polymer-templates/tutorial-template-components.asciidoc#L80)):*
> identifier may also be
indentifier could also be

---

*[documentation/polymer-templates/tutorial-template-components.asciidoc, line 80 at r1](https://reviewable.io:443/reviews/vaadin/flow-and-components-documentation/44#-L8Vqn8lFBJgGiD9gBaI:-L8Vqn8lFBJgGiD9gBaJ:bwgt373) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/c7ec8a2ec1af3e1cbc51187acce1cc2cb23b28cc/documentation/polymer-templates/tutorial-template-components.asciidoc#L80)):*
> In the example above 
Only have `In the example` as above feels like it targes the `MainPage page....` sources part.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow-and-components-documentation/44)*

**Comment by caalador** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[documentation/polymer-templates/tutorial-template-components.asciidoc, line 80 at r1](https://reviewable.io:443/reviews/vaadin/flow-and-components-documentation/44#-L8Vqn8lFBJgGiD9gBaI:-L8WHkVKqRRS53Gg3pPj:bd353te) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/c7ec8a2ec1af3e1cbc51187acce1cc2cb23b28cc/documentation/polymer-templates/tutorial-template-components.asciidoc#L80)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

True.
Is it better now?
</blockquote></details>

should there be a comma after above e.g. `example above, the 'div' element`.
As reading it makes it sound that it's 'example above the div' and not the 'example above'

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow-and-components-documentation/44)*

**Comment by denis-anisimov** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[documentation/polymer-templates/tutorial-template-components.asciidoc, line 80 at r1](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/44#-L8Vqn8lFBJgGiD9gBaI:-L8WIeujAQIwQzonqUqM:b-896fix) ([raw file](https://github.com/vaadin/flow-and-components-documentation/blob/c7ec8a2ec1af3e1cbc51187acce1cc2cb23b28cc/documentation/polymer-templates/tutorial-template-components.asciidoc#L80)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

should there be a comma after above e.g. `example above, the 'div' element`.
As reading it makes it sound that it's 'example above the div' and not the 'example above'
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/44)*

**Comment by caalador** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow-and-components-documentation/44#-:-L8WLmnj9uyO69_gft35:bnfp4nl)*

**Pull request merged**
